// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module equalStep_baseline_atan2_generic_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_in,
        x_in,
        ap_return
);

parameter    ap_ST_fsm_state1 = 60'd1;
parameter    ap_ST_fsm_state2 = 60'd2;
parameter    ap_ST_fsm_state3 = 60'd4;
parameter    ap_ST_fsm_state4 = 60'd8;
parameter    ap_ST_fsm_state5 = 60'd16;
parameter    ap_ST_fsm_state6 = 60'd32;
parameter    ap_ST_fsm_state7 = 60'd64;
parameter    ap_ST_fsm_state8 = 60'd128;
parameter    ap_ST_fsm_state9 = 60'd256;
parameter    ap_ST_fsm_state10 = 60'd512;
parameter    ap_ST_fsm_state11 = 60'd1024;
parameter    ap_ST_fsm_state12 = 60'd2048;
parameter    ap_ST_fsm_state13 = 60'd4096;
parameter    ap_ST_fsm_state14 = 60'd8192;
parameter    ap_ST_fsm_state15 = 60'd16384;
parameter    ap_ST_fsm_state16 = 60'd32768;
parameter    ap_ST_fsm_state17 = 60'd65536;
parameter    ap_ST_fsm_state18 = 60'd131072;
parameter    ap_ST_fsm_state19 = 60'd262144;
parameter    ap_ST_fsm_state20 = 60'd524288;
parameter    ap_ST_fsm_state21 = 60'd1048576;
parameter    ap_ST_fsm_state22 = 60'd2097152;
parameter    ap_ST_fsm_state23 = 60'd4194304;
parameter    ap_ST_fsm_state24 = 60'd8388608;
parameter    ap_ST_fsm_state25 = 60'd16777216;
parameter    ap_ST_fsm_state26 = 60'd33554432;
parameter    ap_ST_fsm_state27 = 60'd67108864;
parameter    ap_ST_fsm_state28 = 60'd134217728;
parameter    ap_ST_fsm_state29 = 60'd268435456;
parameter    ap_ST_fsm_state30 = 60'd536870912;
parameter    ap_ST_fsm_state31 = 60'd1073741824;
parameter    ap_ST_fsm_state32 = 60'd2147483648;
parameter    ap_ST_fsm_state33 = 60'd4294967296;
parameter    ap_ST_fsm_state34 = 60'd8589934592;
parameter    ap_ST_fsm_state35 = 60'd17179869184;
parameter    ap_ST_fsm_state36 = 60'd34359738368;
parameter    ap_ST_fsm_state37 = 60'd68719476736;
parameter    ap_ST_fsm_state38 = 60'd137438953472;
parameter    ap_ST_fsm_state39 = 60'd274877906944;
parameter    ap_ST_fsm_state40 = 60'd549755813888;
parameter    ap_ST_fsm_state41 = 60'd1099511627776;
parameter    ap_ST_fsm_state42 = 60'd2199023255552;
parameter    ap_ST_fsm_state43 = 60'd4398046511104;
parameter    ap_ST_fsm_state44 = 60'd8796093022208;
parameter    ap_ST_fsm_state45 = 60'd17592186044416;
parameter    ap_ST_fsm_state46 = 60'd35184372088832;
parameter    ap_ST_fsm_state47 = 60'd70368744177664;
parameter    ap_ST_fsm_state48 = 60'd140737488355328;
parameter    ap_ST_fsm_state49 = 60'd281474976710656;
parameter    ap_ST_fsm_state50 = 60'd562949953421312;
parameter    ap_ST_fsm_state51 = 60'd1125899906842624;
parameter    ap_ST_fsm_state52 = 60'd2251799813685248;
parameter    ap_ST_fsm_state53 = 60'd4503599627370496;
parameter    ap_ST_fsm_state54 = 60'd9007199254740992;
parameter    ap_ST_fsm_state55 = 60'd18014398509481984;
parameter    ap_ST_fsm_state56 = 60'd36028797018963968;
parameter    ap_ST_fsm_state57 = 60'd72057594037927936;
parameter    ap_ST_fsm_state58 = 60'd144115188075855872;
parameter    ap_ST_fsm_state59 = 60'd288230376151711744;
parameter    ap_ST_fsm_state60 = 60'd576460752303423488;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] y_in;
input  [63:0] x_in;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [59:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln655_fu_172_p2;
reg   [0:0] icmp_ln655_reg_561;
wire   [85:0] x_fu_198_p4;
reg   [85:0] x_reg_568;
wire   [88:0] y_1_fu_265_p3;
reg   [88:0] y_1_reg_573;
wire   [0:0] tmp_1_fu_283_p3;
reg   [0:0] tmp_1_reg_581;
wire    ap_CS_fsm_state28;
wire   [85:0] select_ln702_fu_297_p3;
reg   [85:0] select_ln702_reg_586;
wire   [7:0] trunc_ln702_1_fu_317_p1;
reg   [7:0] trunc_ln702_1_reg_594;
wire   [6:0] sub_ln702_1_fu_321_p2;
reg   [6:0] sub_ln702_1_reg_599;
wire   [0:0] or_ln702_fu_407_p2;
reg   [0:0] or_ln702_reg_607;
wire    ap_CS_fsm_state29;
wire   [0:0] icmp_ln702_3_fu_413_p2;
reg   [0:0] icmp_ln702_3_reg_612;
wire   [6:0] add_ln702_1_fu_419_p2;
reg   [6:0] add_ln702_1_reg_617;
wire   [6:0] sub_ln702_2_fu_424_p2;
reg   [6:0] sub_ln702_2_reg_622;
wire   [63:0] bitcast_ln764_fu_541_p1;
wire    ap_CS_fsm_state30;
wire    grp_atan2_generic_double_Pipeline_1_fu_118_ap_start;
wire    grp_atan2_generic_double_Pipeline_1_fu_118_ap_done;
wire    grp_atan2_generic_double_Pipeline_1_fu_118_ap_idle;
wire    grp_atan2_generic_double_Pipeline_1_fu_118_ap_ready;
wire   [85:0] grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out;
wire    grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out_ap_vld;
wire   [63:0] grp_fu_127_p2;
reg   [63:0] ap_phi_mux_retval_0_phi_fu_106_p8;
reg   [63:0] retval_0_reg_102;
wire    ap_CS_fsm_state60;
wire   [0:0] icmp_ln662_fu_178_p2;
wire   [0:0] icmp_ln702_fu_277_p2;
reg    grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [63:0] data_fu_134_p1;
wire   [63:0] data_1_fu_146_p1;
wire   [10:0] fps_y_exp_fu_150_p3;
wire   [11:0] zext_ln655_fu_158_p1;
wire   [10:0] fps_x_exp_fu_138_p3;
wire   [11:0] add_ln655_fu_162_p2;
wire   [11:0] zext_ln655_1_fu_168_p1;
wire   [11:0] d_exp_fu_184_p2;
wire   [51:0] trunc_ln505_fu_194_p1;
wire   [51:0] trunc_ln505_1_fu_209_p1;
wire   [85:0] y_fu_213_p4;
wire   [10:0] trunc_ln688_fu_190_p1;
wire   [0:0] tmp_fu_227_p3;
wire   [10:0] sub_ln695_fu_235_p2;
wire   [10:0] select_ln695_fu_241_p3;
wire   [88:0] zext_ln681_fu_223_p1;
wire   [88:0] zext_ln695_fu_249_p1;
wire   [88:0] shl_ln695_fu_253_p2;
wire   [88:0] lshr_ln695_fu_259_p2;
wire   [85:0] sub_ln702_fu_291_p2;
wire   [85:0] tmp_3_fu_305_p1;
wire   [85:0] tmp_3_fu_305_p3;
wire   [6:0] trunc_ln702_fu_313_p1;
wire   [6:0] add_ln702_fu_327_p2;
wire   [5:0] tmp_2_fu_332_p4;
wire   [6:0] sub_ln702_4_fu_348_p2;
wire   [85:0] zext_ln702_fu_353_p1;
wire   [85:0] lshr_ln702_2_fu_357_p2;
wire   [85:0] and_ln702_1_fu_363_p2;
wire   [0:0] icmp_ln702_1_fu_342_p2;
wire   [0:0] icmp_ln702_2_fu_368_p2;
wire   [0:0] tmp_4_fu_380_p3;
wire   [0:0] tmp_5_fu_394_p3;
wire   [0:0] xor_ln702_fu_388_p2;
wire   [0:0] and_ln702_fu_401_p2;
wire   [0:0] phi_ln702_fu_374_p2;
wire  signed [31:0] sext_ln702_fu_429_p1;
wire   [85:0] zext_ln702_1_fu_432_p1;
wire  signed [31:0] sext_ln702_1_fu_441_p1;
wire   [85:0] zext_ln702_4_fu_444_p1;
wire   [85:0] lshr_ln702_fu_436_p2;
wire   [85:0] shl_ln702_fu_448_p2;
wire   [63:0] trunc_ln702_2_fu_453_p1;
wire   [63:0] trunc_ln702_3_fu_457_p1;
wire   [63:0] select_ln702_1_fu_461_p3;
wire   [63:0] zext_ln702_2_fu_468_p1;
wire   [63:0] add_ln702_2_fu_471_p2;
wire   [62:0] lshr_ln702_1_fu_477_p4;
wire   [0:0] tmp_6_fu_491_p3;
wire   [7:0] sub_ln702_3_fu_507_p2;
wire  signed [10:0] sext_ln702_2_fu_512_p1;
wire   [10:0] select_ln702_2_fu_499_p3;
wire   [10:0] add_ln702_3_fu_516_p2;
wire   [63:0] zext_ln702_3_fu_487_p1;
wire   [11:0] tmp_9_fu_522_p3;
wire   [63:0] LD_fu_529_p5;
reg   [63:0] ap_return_preg;
reg   [59:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire   [85:0] tmp_3_fu_305_p0;
wire   [0:0] tmp_3_fu_305_p2;
wire   [0:0] tmp_5_fu_394_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 60'd1;
#0 grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg = 1'b0;
#0 ap_return_preg = 64'd0;
end

equalStep_baseline_atan2_generic_double_Pipeline_1 grp_atan2_generic_double_Pipeline_1_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_atan2_generic_double_Pipeline_1_fu_118_ap_start),
    .ap_done(grp_atan2_generic_double_Pipeline_1_fu_118_ap_done),
    .ap_idle(grp_atan2_generic_double_Pipeline_1_fu_118_ap_idle),
    .ap_ready(grp_atan2_generic_double_Pipeline_1_fu_118_ap_ready),
    .y_1(y_1_reg_573),
    .zext_ln681(x_reg_568),
    .z_2_out(grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out),
    .z_2_out_ap_vld(grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out_ap_vld)
);

equalStep_baseline_ddiv_64ns_64ns_64_31_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_31_no_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(y_in),
    .din1(x_in),
    .ce(1'b1),
    .dout(grp_fu_127_p2)
);

equalStep_baseline_ctlz_86_86_1_1 #(
    .din_WIDTH( 86 ),
    .dout_WIDTH( 86 ))
ctlz_86_86_1_1_U17(
    .din(tmp_3_fu_305_p1),
    .dout(tmp_3_fu_305_p3)
);

equalStep_baseline_bitselect_1ns_86ns_7ns_1_1_1 #(
    .DATAWIDTH( 86 ),
    .ADDRWIDTH( 7 ))
bitselect_1ns_86ns_7ns_1_1_1_U18(
    .din(select_ln702_reg_586),
    .sel(add_ln702_fu_327_p2),
    .dout(tmp_5_fu_394_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state60)) begin
            ap_return_preg <= ap_phi_mux_retval_0_phi_fu_106_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln655_fu_172_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln662_fu_178_p2 == 1'd0))) begin
            grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_atan2_generic_double_Pipeline_1_fu_118_ap_ready == 1'b1)) begin
            grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state28) & (icmp_ln702_fu_277_p2 == 1'd1)) | ((icmp_ln655_fu_172_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln662_fu_178_p2 == 1'd1)))) begin
        retval_0_reg_102 <= 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        retval_0_reg_102 <= bitcast_ln764_fu_541_p1;
    end else if (((icmp_ln655_reg_561 == 1'd1) & (1'b1 == ap_CS_fsm_state60))) begin
        retval_0_reg_102 <= grp_fu_127_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        add_ln702_1_reg_617 <= add_ln702_1_fu_419_p2;
        icmp_ln702_3_reg_612 <= icmp_ln702_3_fu_413_p2;
        or_ln702_reg_607 <= or_ln702_fu_407_p2;
        sub_ln702_2_reg_622 <= sub_ln702_2_fu_424_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln655_reg_561 <= icmp_ln655_fu_172_p2;
        x_reg_568[84 : 33] <= x_fu_198_p4[84 : 33];
        y_1_reg_573 <= y_1_fu_265_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        select_ln702_reg_586 <= select_ln702_fu_297_p3;
        sub_ln702_1_reg_599 <= sub_ln702_1_fu_321_p2;
        tmp_1_reg_581 <= grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out[32'd85];
        trunc_ln702_1_reg_594 <= trunc_ln702_1_fu_317_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_atan2_generic_double_Pipeline_1_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state60) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln655_reg_561 == 1'd1) & (1'b1 == ap_CS_fsm_state60))) begin
        ap_phi_mux_retval_0_phi_fu_106_p8 = grp_fu_127_p2;
    end else begin
        ap_phi_mux_retval_0_phi_fu_106_p8 = retval_0_reg_102;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        ap_return = ap_phi_mux_retval_0_phi_fu_106_p8;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln655_fu_172_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln662_fu_178_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end else if (((icmp_ln655_fu_172_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln662_fu_178_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln655_fu_172_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_atan2_generic_double_Pipeline_1_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b1 == ap_CS_fsm_state28) & (icmp_ln702_fu_277_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_529_p5 = {{tmp_9_fu_522_p3}, {zext_ln702_3_fu_487_p1[51:0]}};

assign add_ln655_fu_162_p2 = (zext_ln655_fu_158_p1 + 12'd27);

assign add_ln702_1_fu_419_p2 = ($signed(sub_ln702_1_reg_599) + $signed(7'd74));

assign add_ln702_2_fu_471_p2 = (select_ln702_1_fu_461_p3 + zext_ln702_2_fu_468_p1);

assign add_ln702_3_fu_516_p2 = ($signed(sext_ln702_2_fu_512_p1) + $signed(select_ln702_2_fu_499_p3));

assign add_ln702_fu_327_p2 = ($signed(sub_ln702_1_reg_599) + $signed(7'd75));

assign and_ln702_1_fu_363_p2 = (select_ln702_reg_586 & lshr_ln702_2_fu_357_p2);

assign and_ln702_fu_401_p2 = (xor_ln702_fu_388_p2 & tmp_5_fu_394_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign bitcast_ln764_fu_541_p1 = LD_fu_529_p5;

assign d_exp_fu_184_p2 = (zext_ln655_1_fu_168_p1 - zext_ln655_fu_158_p1);

assign data_1_fu_146_p1 = y_in;

assign data_fu_134_p1 = x_in;

assign fps_x_exp_fu_138_p3 = {{data_fu_134_p1[62:52]}};

assign fps_y_exp_fu_150_p3 = {{data_1_fu_146_p1[62:52]}};

assign grp_atan2_generic_double_Pipeline_1_fu_118_ap_start = grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg;

assign icmp_ln655_fu_172_p2 = ((add_ln655_fu_162_p2 < zext_ln655_1_fu_168_p1) ? 1'b1 : 1'b0);

assign icmp_ln662_fu_178_p2 = ((fps_y_exp_fu_150_p3 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln702_1_fu_342_p2 = (($signed(tmp_2_fu_332_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln702_2_fu_368_p2 = ((and_ln702_1_fu_363_p2 != 86'd0) ? 1'b1 : 1'b0);

assign icmp_ln702_3_fu_413_p2 = (($signed(add_ln702_fu_327_p2) > $signed(7'd0)) ? 1'b1 : 1'b0);

assign icmp_ln702_fu_277_p2 = ((grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out == 86'd0) ? 1'b1 : 1'b0);

assign lshr_ln695_fu_259_p2 = zext_ln681_fu_223_p1 >> zext_ln695_fu_249_p1;

assign lshr_ln702_1_fu_477_p4 = {{add_ln702_2_fu_471_p2[63:1]}};

assign lshr_ln702_2_fu_357_p2 = 86'd77371252455336267181195263 >> zext_ln702_fu_353_p1;

assign lshr_ln702_fu_436_p2 = select_ln702_reg_586 >> zext_ln702_1_fu_432_p1;

assign or_ln702_fu_407_p2 = (phi_ln702_fu_374_p2 | and_ln702_fu_401_p2);

assign phi_ln702_fu_374_p2 = (icmp_ln702_2_fu_368_p2 & icmp_ln702_1_fu_342_p2);

assign select_ln695_fu_241_p3 = ((tmp_fu_227_p3[0:0] == 1'b1) ? sub_ln695_fu_235_p2 : trunc_ln688_fu_190_p1);

assign select_ln702_1_fu_461_p3 = ((icmp_ln702_3_reg_612[0:0] == 1'b1) ? trunc_ln702_2_fu_453_p1 : trunc_ln702_3_fu_457_p1);

assign select_ln702_2_fu_499_p3 = ((tmp_6_fu_491_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign select_ln702_fu_297_p3 = ((tmp_1_fu_283_p3[0:0] == 1'b1) ? sub_ln702_fu_291_p2 : grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out);

assign sext_ln702_1_fu_441_p1 = $signed(sub_ln702_2_reg_622);

assign sext_ln702_2_fu_512_p1 = $signed(sub_ln702_3_fu_507_p2);

assign sext_ln702_fu_429_p1 = $signed(add_ln702_1_reg_617);

assign shl_ln695_fu_253_p2 = zext_ln681_fu_223_p1 << zext_ln695_fu_249_p1;

assign shl_ln702_fu_448_p2 = select_ln702_reg_586 << zext_ln702_4_fu_444_p1;

assign sub_ln695_fu_235_p2 = (11'd0 - trunc_ln688_fu_190_p1);

assign sub_ln702_1_fu_321_p2 = ($signed(7'd86) - $signed(trunc_ln702_fu_313_p1));

assign sub_ln702_2_fu_424_p2 = (7'd54 - sub_ln702_1_reg_599);

assign sub_ln702_3_fu_507_p2 = (8'd1 - trunc_ln702_1_reg_594);

assign sub_ln702_4_fu_348_p2 = (7'd12 - sub_ln702_1_reg_599);

assign sub_ln702_fu_291_p2 = (86'd0 - grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out);

assign tmp_1_fu_283_p3 = grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out[32'd85];

assign tmp_2_fu_332_p4 = {{add_ln702_fu_327_p2[6:1]}};

assign tmp_3_fu_305_p1 = ((tmp_1_fu_283_p3[0:0] == 1'b1) ? sub_ln702_fu_291_p2 : grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out);

assign tmp_4_fu_380_p3 = add_ln702_fu_327_p2[32'd6];

assign tmp_6_fu_491_p3 = add_ln702_2_fu_471_p2[32'd54];

assign tmp_9_fu_522_p3 = {{tmp_1_reg_581}, {add_ln702_3_fu_516_p2}};

assign tmp_fu_227_p3 = d_exp_fu_184_p2[32'd11];

assign trunc_ln505_1_fu_209_p1 = data_1_fu_146_p1[51:0];

assign trunc_ln505_fu_194_p1 = data_fu_134_p1[51:0];

assign trunc_ln688_fu_190_p1 = d_exp_fu_184_p2[10:0];

assign trunc_ln702_1_fu_317_p1 = tmp_3_fu_305_p3[7:0];

assign trunc_ln702_2_fu_453_p1 = lshr_ln702_fu_436_p2[63:0];

assign trunc_ln702_3_fu_457_p1 = shl_ln702_fu_448_p2[63:0];

assign trunc_ln702_fu_313_p1 = tmp_3_fu_305_p3[6:0];

assign x_fu_198_p4 = {{{{1'd1}, {trunc_ln505_fu_194_p1}}}, {33'd0}};

assign xor_ln702_fu_388_p2 = (tmp_4_fu_380_p3 ^ 1'd1);

assign y_1_fu_265_p3 = ((tmp_fu_227_p3[0:0] == 1'b1) ? shl_ln695_fu_253_p2 : lshr_ln695_fu_259_p2);

assign y_fu_213_p4 = {{{{1'd1}, {trunc_ln505_1_fu_209_p1}}}, {33'd0}};

assign zext_ln655_1_fu_168_p1 = fps_x_exp_fu_138_p3;

assign zext_ln655_fu_158_p1 = fps_y_exp_fu_150_p3;

assign zext_ln681_fu_223_p1 = y_fu_213_p4;

assign zext_ln695_fu_249_p1 = select_ln695_fu_241_p3;

assign zext_ln702_1_fu_432_p1 = $unsigned(sext_ln702_fu_429_p1);

assign zext_ln702_2_fu_468_p1 = or_ln702_reg_607;

assign zext_ln702_3_fu_487_p1 = lshr_ln702_1_fu_477_p4;

assign zext_ln702_4_fu_444_p1 = $unsigned(sext_ln702_1_fu_441_p1);

assign zext_ln702_fu_353_p1 = sub_ln702_4_fu_348_p2;

always @ (posedge ap_clk) begin
    x_reg_568[32:0] <= 33'b000000000000000000000000000000000;
    x_reg_568[85] <= 1'b1;
end

endmodule //equalStep_baseline_atan2_generic_double_s
