-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity equalStep_baseline_atan2_generic_double_Pipeline_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    y_1 : IN STD_LOGIC_VECTOR (88 downto 0);
    zext_ln681 : IN STD_LOGIC_VECTOR (85 downto 0);
    z_2_out : OUT STD_LOGIC_VECTOR (85 downto 0);
    z_2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of equalStep_baseline_atan2_generic_double_Pipeline_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv86_0 : STD_LOGIC_VECTOR (85 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_58 : STD_LOGIC_VECTOR (6 downto 0) := "1011000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln138_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal cordic_ctab_table_128_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal cordic_ctab_table_128_q0 : STD_LOGIC_VECTOR (125 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal k_2_reg_331 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln138_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_fu_167_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_reg_345 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_2_fu_252_p2 : STD_LOGIC_VECTOR (84 downto 0);
    signal b_2_reg_350 : STD_LOGIC_VECTOR (84 downto 0);
    signal zext_ln138_fu_151_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal a_fu_64 : STD_LOGIC_VECTOR (88 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal x_fu_196_p3 : STD_LOGIC_VECTOR (88 downto 0);
    signal zext_ln681_cast_fu_112_p1 : STD_LOGIC_VECTOR (88 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal a_1_fu_68 : STD_LOGIC_VECTOR (88 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal y_fu_222_p3 : STD_LOGIC_VECTOR (88 downto 0);
    signal a_2_fu_72 : STD_LOGIC_VECTOR (85 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal z_fu_286_p3 : STD_LOGIC_VECTOR (85 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal k_fu_76 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln138_fu_145_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_k_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal cordic_ctab_table_128_ce0_local : STD_LOGIC;
    signal zext_ln159_fu_175_p1 : STD_LOGIC_VECTOR (88 downto 0);
    signal y_s_fu_178_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal sub_ln101_fu_184_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal add_ln101_fu_190_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal x_s_fu_204_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal add_ln101_1_fu_216_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal sub_ln101_1_fu_210_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal tmp_fu_240_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_fu_230_p4 : STD_LOGIC_VECTOR (84 downto 0);
    signal zext_ln163_fu_248_p1 : STD_LOGIC_VECTOR (84 downto 0);
    signal zext_ln164_fu_271_p1 : STD_LOGIC_VECTOR (85 downto 0);
    signal sub_ln101_2_fu_274_p2 : STD_LOGIC_VECTOR (85 downto 0);
    signal add_ln101_2_fu_280_p2 : STD_LOGIC_VECTOR (85 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component equalStep_baseline_atan2_generic_double_Pipeline_1_cordic_ctab_table_128_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (125 downto 0) );
    end component;


    component equalStep_baseline_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    cordic_ctab_table_128_U : component equalStep_baseline_atan2_generic_double_Pipeline_1_cordic_ctab_table_128_ROM_AUTO_1R
    generic map (
        DataWidth => 126,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => cordic_ctab_table_128_address0,
        ce0 => cordic_ctab_table_128_ce0_local,
        q0 => cordic_ctab_table_128_q0);

    flow_control_loop_pipe_sequential_init_U : component equalStep_baseline_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    a_1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    a_1_fu_68 <= y_1;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    a_1_fu_68 <= y_fu_222_p3;
                end if;
            end if; 
        end if;
    end process;

    a_2_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    a_2_fu_72 <= ap_const_lv86_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    a_2_fu_72 <= z_fu_286_p3;
                end if;
            end if; 
        end if;
    end process;

    a_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    a_fu_64 <= zext_ln681_cast_fu_112_p1;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    a_fu_64 <= x_fu_196_p3;
                end if;
            end if; 
        end if;
    end process;

    k_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln138_fu_139_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_76 <= add_ln138_fu_145_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_76 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_reg_345 <= a_1_fu_68(88 downto 88);
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                b_2_reg_350 <= b_2_fu_252_p2;
                icmp_ln138_reg_336 <= icmp_ln138_fu_139_p2;
                k_2_reg_331 <= ap_sig_allocacmp_k_2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_fu_167_p3 <= a_1_fu_68(88 downto 88);
    add_ln101_1_fu_216_p2 <= std_logic_vector(unsigned(x_s_fu_204_p2) + unsigned(a_1_fu_68));
    add_ln101_2_fu_280_p2 <= std_logic_vector(unsigned(zext_ln164_fu_271_p1) + unsigned(a_2_fu_72));
    add_ln101_fu_190_p2 <= std_logic_vector(unsigned(y_s_fu_178_p2) + unsigned(a_fu_64));
    add_ln138_fu_145_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_2) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln138_fu_139_p2)
    begin
        if (((icmp_ln138_fu_139_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_76)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_k_2 <= k_fu_76;
        end if; 
    end process;

    b_2_fu_252_p2 <= std_logic_vector(unsigned(trunc_ln1_fu_230_p4) + unsigned(zext_ln163_fu_248_p1));
    cordic_ctab_table_128_address0 <= zext_ln138_fu_151_p1(7 - 1 downto 0);

    cordic_ctab_table_128_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cordic_ctab_table_128_ce0_local <= ap_const_logic_1;
        else 
            cordic_ctab_table_128_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln138_fu_139_p2 <= "1" when (ap_sig_allocacmp_k_2 = ap_const_lv7_58) else "0";
    sub_ln101_1_fu_210_p2 <= std_logic_vector(unsigned(a_1_fu_68) - unsigned(x_s_fu_204_p2));
    sub_ln101_2_fu_274_p2 <= std_logic_vector(unsigned(a_2_fu_72) - unsigned(zext_ln164_fu_271_p1));
    sub_ln101_fu_184_p2 <= std_logic_vector(unsigned(a_fu_64) - unsigned(y_s_fu_178_p2));
    tmp_fu_240_p3 <= cordic_ctab_table_128_q0(40 downto 40);
    trunc_ln1_fu_230_p4 <= cordic_ctab_table_128_q0(125 downto 41);
    x_fu_196_p3 <= 
        sub_ln101_fu_184_p2 when (add_fu_167_p3(0) = '1') else 
        add_ln101_fu_190_p2;
    x_s_fu_204_p2 <= std_logic_vector(shift_right(signed(a_fu_64),to_integer(unsigned('0' & zext_ln159_fu_175_p1(31-1 downto 0)))));
    y_fu_222_p3 <= 
        add_ln101_1_fu_216_p2 when (add_fu_167_p3(0) = '1') else 
        sub_ln101_1_fu_210_p2;
    y_s_fu_178_p2 <= std_logic_vector(shift_right(signed(a_1_fu_68),to_integer(unsigned('0' & zext_ln159_fu_175_p1(31-1 downto 0)))));
    z_2_out <= a_2_fu_72;

    z_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln138_reg_336, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((icmp_ln138_reg_336 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            z_2_out_ap_vld <= ap_const_logic_1;
        else 
            z_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    z_fu_286_p3 <= 
        sub_ln101_2_fu_274_p2 when (add_reg_345(0) = '1') else 
        add_ln101_2_fu_280_p2;
    zext_ln138_fu_151_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_2),64));
    zext_ln159_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_2_reg_331),89));
    zext_ln163_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_240_p3),85));
    zext_ln164_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_2_reg_350),86));
    zext_ln681_cast_fu_112_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln681),89));
end behav;
