-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity equalStep_baseline_atan2_generic_double_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    y_in : IN STD_LOGIC_VECTOR (63 downto 0);
    x_in : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of equalStep_baseline_atan2_generic_double_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (59 downto 0) := "000000000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (59 downto 0) := "000000000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (59 downto 0) := "000000000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (59 downto 0) := "000000001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (59 downto 0) := "000000010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (59 downto 0) := "000000100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (59 downto 0) := "000001000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (59 downto 0) := "000010000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state57 : STD_LOGIC_VECTOR (59 downto 0) := "000100000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state58 : STD_LOGIC_VECTOR (59 downto 0) := "001000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state59 : STD_LOGIC_VECTOR (59 downto 0) := "010000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state60 : STD_LOGIC_VECTOR (59 downto 0) := "100000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv12_1B : STD_LOGIC_VECTOR (11 downto 0) := "000000011011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv86_0 : STD_LOGIC_VECTOR (85 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_55 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010101";
    constant ap_const_lv7_56 : STD_LOGIC_VECTOR (6 downto 0) := "1010110";
    constant ap_const_lv7_4B : STD_LOGIC_VECTOR (6 downto 0) := "1001011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_C : STD_LOGIC_VECTOR (6 downto 0) := "0001100";
    constant ap_const_lv86_3FFFFFFFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (85 downto 0) := "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_4A : STD_LOGIC_VECTOR (6 downto 0) := "1001010";
    constant ap_const_lv7_36 : STD_LOGIC_VECTOR (6 downto 0) := "0110110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv11_3FE : STD_LOGIC_VECTOR (10 downto 0) := "01111111110";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln655_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln655_reg_561 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_198_p4 : STD_LOGIC_VECTOR (85 downto 0);
    signal x_reg_568 : STD_LOGIC_VECTOR (85 downto 0);
    signal y_1_fu_265_p3 : STD_LOGIC_VECTOR (88 downto 0);
    signal y_1_reg_573 : STD_LOGIC_VECTOR (88 downto 0);
    signal tmp_1_fu_283_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_581 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal select_ln702_fu_297_p3 : STD_LOGIC_VECTOR (85 downto 0);
    signal select_ln702_reg_586 : STD_LOGIC_VECTOR (85 downto 0);
    signal trunc_ln702_1_fu_317_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln702_1_reg_594 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln702_1_fu_321_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln702_1_reg_599 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln702_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln702_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal icmp_ln702_3_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln702_3_reg_612 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln702_1_fu_419_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln702_1_reg_617 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln702_2_fu_424_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln702_2_reg_622 : STD_LOGIC_VECTOR (6 downto 0);
    signal bitcast_ln764_fu_541_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state30 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal grp_atan2_generic_double_Pipeline_1_fu_118_ap_start : STD_LOGIC;
    signal grp_atan2_generic_double_Pipeline_1_fu_118_ap_done : STD_LOGIC;
    signal grp_atan2_generic_double_Pipeline_1_fu_118_ap_idle : STD_LOGIC;
    signal grp_atan2_generic_double_Pipeline_1_fu_118_ap_ready : STD_LOGIC;
    signal grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out : STD_LOGIC_VECTOR (85 downto 0);
    signal grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out_ap_vld : STD_LOGIC;
    signal grp_fu_127_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_mux_retval_0_phi_fu_106_p8 : STD_LOGIC_VECTOR (63 downto 0);
    signal retval_0_reg_102 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state60 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state60 : signal is "none";
    signal icmp_ln662_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln702_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal data_fu_134_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_1_fu_146_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal fps_y_exp_fu_150_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln655_fu_158_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal fps_x_exp_fu_138_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln655_fu_162_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln655_1_fu_168_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal d_exp_fu_184_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln505_fu_194_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln505_1_fu_209_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal y_fu_213_p4 : STD_LOGIC_VECTOR (85 downto 0);
    signal trunc_ln688_fu_190_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_227_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln695_fu_235_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln695_fu_241_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln681_fu_223_p1 : STD_LOGIC_VECTOR (88 downto 0);
    signal zext_ln695_fu_249_p1 : STD_LOGIC_VECTOR (88 downto 0);
    signal shl_ln695_fu_253_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal lshr_ln695_fu_259_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal sub_ln702_fu_291_p2 : STD_LOGIC_VECTOR (85 downto 0);
    signal tmp_3_fu_305_p1 : STD_LOGIC_VECTOR (85 downto 0);
    signal tmp_3_fu_305_p3 : STD_LOGIC_VECTOR (85 downto 0);
    signal trunc_ln702_fu_313_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln702_fu_327_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_fu_332_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln702_4_fu_348_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln702_fu_353_p1 : STD_LOGIC_VECTOR (85 downto 0);
    signal lshr_ln702_2_fu_357_p2 : STD_LOGIC_VECTOR (85 downto 0);
    signal and_ln702_1_fu_363_p2 : STD_LOGIC_VECTOR (85 downto 0);
    signal icmp_ln702_1_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln702_2_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_380_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_394_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln702_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln702_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln702_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln702_fu_429_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln702_1_fu_432_p1 : STD_LOGIC_VECTOR (85 downto 0);
    signal sext_ln702_1_fu_441_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln702_4_fu_444_p1 : STD_LOGIC_VECTOR (85 downto 0);
    signal lshr_ln702_fu_436_p2 : STD_LOGIC_VECTOR (85 downto 0);
    signal shl_ln702_fu_448_p2 : STD_LOGIC_VECTOR (85 downto 0);
    signal trunc_ln702_2_fu_453_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln702_3_fu_457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln702_1_fu_461_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln702_2_fu_468_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln702_2_fu_471_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln702_1_fu_477_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_6_fu_491_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln702_3_fu_507_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln702_2_fu_512_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln702_2_fu_499_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln702_3_fu_516_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln702_3_fu_487_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_fu_522_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal LD_fu_529_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (59 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ST_fsm_state39_blk : STD_LOGIC;
    signal ap_ST_fsm_state40_blk : STD_LOGIC;
    signal ap_ST_fsm_state41_blk : STD_LOGIC;
    signal ap_ST_fsm_state42_blk : STD_LOGIC;
    signal ap_ST_fsm_state43_blk : STD_LOGIC;
    signal ap_ST_fsm_state44_blk : STD_LOGIC;
    signal ap_ST_fsm_state45_blk : STD_LOGIC;
    signal ap_ST_fsm_state46_blk : STD_LOGIC;
    signal ap_ST_fsm_state47_blk : STD_LOGIC;
    signal ap_ST_fsm_state48_blk : STD_LOGIC;
    signal ap_ST_fsm_state49_blk : STD_LOGIC;
    signal ap_ST_fsm_state50_blk : STD_LOGIC;
    signal ap_ST_fsm_state51_blk : STD_LOGIC;
    signal ap_ST_fsm_state52_blk : STD_LOGIC;
    signal ap_ST_fsm_state53_blk : STD_LOGIC;
    signal ap_ST_fsm_state54_blk : STD_LOGIC;
    signal ap_ST_fsm_state55_blk : STD_LOGIC;
    signal ap_ST_fsm_state56_blk : STD_LOGIC;
    signal ap_ST_fsm_state57_blk : STD_LOGIC;
    signal ap_ST_fsm_state58_blk : STD_LOGIC;
    signal ap_ST_fsm_state59_blk : STD_LOGIC;
    signal ap_ST_fsm_state60_blk : STD_LOGIC;
    signal tmp_3_fu_305_p0 : STD_LOGIC_VECTOR (85 downto 0);
    signal tmp_3_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_394_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component equalStep_baseline_atan2_generic_double_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y_1 : IN STD_LOGIC_VECTOR (88 downto 0);
        zext_ln681 : IN STD_LOGIC_VECTOR (85 downto 0);
        z_2_out : OUT STD_LOGIC_VECTOR (85 downto 0);
        z_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component equalStep_baseline_ddiv_64ns_64ns_64_31_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component equalStep_baseline_ctlz_86_86_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (85 downto 0);
        dout : OUT STD_LOGIC_VECTOR (85 downto 0) );
    end component;


    component equalStep_baseline_bitselect_1ns_86ns_7ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (85 downto 0);
        sel : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_atan2_generic_double_Pipeline_1_fu_118 : component equalStep_baseline_atan2_generic_double_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_atan2_generic_double_Pipeline_1_fu_118_ap_start,
        ap_done => grp_atan2_generic_double_Pipeline_1_fu_118_ap_done,
        ap_idle => grp_atan2_generic_double_Pipeline_1_fu_118_ap_idle,
        ap_ready => grp_atan2_generic_double_Pipeline_1_fu_118_ap_ready,
        y_1 => y_1_reg_573,
        zext_ln681 => x_reg_568,
        z_2_out => grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out,
        z_2_out_ap_vld => grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out_ap_vld);

    ddiv_64ns_64ns_64_31_no_dsp_1_U16 : component equalStep_baseline_ddiv_64ns_64ns_64_31_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 31,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => y_in,
        din1 => x_in,
        ce => ap_const_logic_1,
        dout => grp_fu_127_p2);

    ctlz_86_86_1_1_U17 : component equalStep_baseline_ctlz_86_86_1_1
    generic map (
        din_WIDTH => 86,
        dout_WIDTH => 86)
    port map (
        din => tmp_3_fu_305_p1,
        dout => tmp_3_fu_305_p3);

    bitselect_1ns_86ns_7ns_1_1_1_U18 : component equalStep_baseline_bitselect_1ns_86ns_7ns_1_1_1
    generic map (
        DATAWIDTH => 86,
        ADDRWIDTH => 7)
    port map (
        din => select_ln702_reg_586,
        sel => add_ln702_fu_327_p2,
        dout => tmp_5_fu_394_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv64_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state60)) then 
                    ap_return_preg <= ap_phi_mux_retval_0_phi_fu_106_p8;
                end if; 
            end if;
        end if;
    end process;


    grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln655_fu_172_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln662_fu_178_p2 = ap_const_lv1_0))) then 
                    grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_atan2_generic_double_Pipeline_1_fu_118_ap_ready = ap_const_logic_1)) then 
                    grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    retval_0_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state28) and (icmp_ln702_fu_277_p2 = ap_const_lv1_1)) or ((icmp_ln655_fu_172_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln662_fu_178_p2 = ap_const_lv1_1)))) then 
                retval_0_reg_102 <= ap_const_lv64_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
                retval_0_reg_102 <= bitcast_ln764_fu_541_p1;
            elsif (((icmp_ln655_reg_561 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state60))) then 
                retval_0_reg_102 <= grp_fu_127_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state29)) then
                add_ln702_1_reg_617 <= add_ln702_1_fu_419_p2;
                icmp_ln702_3_reg_612 <= icmp_ln702_3_fu_413_p2;
                or_ln702_reg_607 <= or_ln702_fu_407_p2;
                sub_ln702_2_reg_622 <= sub_ln702_2_fu_424_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln655_reg_561 <= icmp_ln655_fu_172_p2;
                    x_reg_568(84 downto 33) <= x_fu_198_p4(84 downto 33);
                y_1_reg_573 <= y_1_fu_265_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state28)) then
                select_ln702_reg_586 <= select_ln702_fu_297_p3;
                sub_ln702_1_reg_599 <= sub_ln702_1_fu_321_p2;
                tmp_1_reg_581 <= grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out(85 downto 85);
                trunc_ln702_1_reg_594 <= trunc_ln702_1_fu_317_p1;
            end if;
        end if;
    end process;
    x_reg_568(32 downto 0) <= "000000000000000000000000000000000";
    x_reg_568(85) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln655_fu_172_p2, ap_CS_fsm_state28, grp_atan2_generic_double_Pipeline_1_fu_118_ap_done, icmp_ln662_fu_178_p2, icmp_ln702_fu_277_p2, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln655_fu_172_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln662_fu_178_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state60;
                elsif (((icmp_ln655_fu_172_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln662_fu_178_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln655_fu_172_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state31;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_atan2_generic_double_Pipeline_1_fu_118_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state28) and (icmp_ln702_fu_277_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state60;
                else
                    ap_NS_fsm <= ap_ST_fsm_state29;
                end if;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state60;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state50;
            when ap_ST_fsm_state50 => 
                ap_NS_fsm <= ap_ST_fsm_state51;
            when ap_ST_fsm_state51 => 
                ap_NS_fsm <= ap_ST_fsm_state52;
            when ap_ST_fsm_state52 => 
                ap_NS_fsm <= ap_ST_fsm_state53;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                ap_NS_fsm <= ap_ST_fsm_state55;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state57;
            when ap_ST_fsm_state57 => 
                ap_NS_fsm <= ap_ST_fsm_state58;
            when ap_ST_fsm_state58 => 
                ap_NS_fsm <= ap_ST_fsm_state59;
            when ap_ST_fsm_state59 => 
                ap_NS_fsm <= ap_ST_fsm_state60;
            when ap_ST_fsm_state60 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    LD_fu_529_p5 <= (tmp_9_fu_522_p3 & zext_ln702_3_fu_487_p1(51 downto 0));
    add_ln655_fu_162_p2 <= std_logic_vector(unsigned(zext_ln655_fu_158_p1) + unsigned(ap_const_lv12_1B));
    add_ln702_1_fu_419_p2 <= std_logic_vector(unsigned(sub_ln702_1_reg_599) + unsigned(ap_const_lv7_4A));
    add_ln702_2_fu_471_p2 <= std_logic_vector(unsigned(select_ln702_1_fu_461_p3) + unsigned(zext_ln702_2_fu_468_p1));
    add_ln702_3_fu_516_p2 <= std_logic_vector(signed(sext_ln702_2_fu_512_p1) + signed(select_ln702_2_fu_499_p3));
    add_ln702_fu_327_p2 <= std_logic_vector(unsigned(sub_ln702_1_reg_599) + unsigned(ap_const_lv7_4B));
    and_ln702_1_fu_363_p2 <= (select_ln702_reg_586 and lshr_ln702_2_fu_357_p2);
    and_ln702_fu_401_p2 <= (xor_ln702_fu_388_p2 and tmp_5_fu_394_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28);
    ap_CS_fsm_state30 <= ap_CS_fsm(29);
    ap_CS_fsm_state60 <= ap_CS_fsm(59);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_atan2_generic_double_Pipeline_1_fu_118_ap_done)
    begin
        if ((grp_atan2_generic_double_Pipeline_1_fu_118_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state39_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state40_blk <= ap_const_logic_0;
    ap_ST_fsm_state41_blk <= ap_const_logic_0;
    ap_ST_fsm_state42_blk <= ap_const_logic_0;
    ap_ST_fsm_state43_blk <= ap_const_logic_0;
    ap_ST_fsm_state44_blk <= ap_const_logic_0;
    ap_ST_fsm_state45_blk <= ap_const_logic_0;
    ap_ST_fsm_state46_blk <= ap_const_logic_0;
    ap_ST_fsm_state47_blk <= ap_const_logic_0;
    ap_ST_fsm_state48_blk <= ap_const_logic_0;
    ap_ST_fsm_state49_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state50_blk <= ap_const_logic_0;
    ap_ST_fsm_state51_blk <= ap_const_logic_0;
    ap_ST_fsm_state52_blk <= ap_const_logic_0;
    ap_ST_fsm_state53_blk <= ap_const_logic_0;
    ap_ST_fsm_state54_blk <= ap_const_logic_0;
    ap_ST_fsm_state55_blk <= ap_const_logic_0;
    ap_ST_fsm_state56_blk <= ap_const_logic_0;
    ap_ST_fsm_state57_blk <= ap_const_logic_0;
    ap_ST_fsm_state58_blk <= ap_const_logic_0;
    ap_ST_fsm_state59_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state60_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state60)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state60) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_retval_0_phi_fu_106_p8_assign_proc : process(icmp_ln655_reg_561, grp_fu_127_p2, retval_0_reg_102, ap_CS_fsm_state60)
    begin
        if (((icmp_ln655_reg_561 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state60))) then 
            ap_phi_mux_retval_0_phi_fu_106_p8 <= grp_fu_127_p2;
        else 
            ap_phi_mux_retval_0_phi_fu_106_p8 <= retval_0_reg_102;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state60)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state60)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_retval_0_phi_fu_106_p8, ap_CS_fsm_state60, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state60)) then 
            ap_return <= ap_phi_mux_retval_0_phi_fu_106_p8;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    bitcast_ln764_fu_541_p1 <= LD_fu_529_p5;
    d_exp_fu_184_p2 <= std_logic_vector(unsigned(zext_ln655_1_fu_168_p1) - unsigned(zext_ln655_fu_158_p1));
    data_1_fu_146_p1 <= y_in;
    data_fu_134_p1 <= x_in;
    fps_x_exp_fu_138_p3 <= data_fu_134_p1(62 downto 52);
    fps_y_exp_fu_150_p3 <= data_1_fu_146_p1(62 downto 52);
    grp_atan2_generic_double_Pipeline_1_fu_118_ap_start <= grp_atan2_generic_double_Pipeline_1_fu_118_ap_start_reg;
    icmp_ln655_fu_172_p2 <= "1" when (unsigned(add_ln655_fu_162_p2) < unsigned(zext_ln655_1_fu_168_p1)) else "0";
    icmp_ln662_fu_178_p2 <= "1" when (fps_y_exp_fu_150_p3 = ap_const_lv11_0) else "0";
    icmp_ln702_1_fu_342_p2 <= "1" when (signed(tmp_2_fu_332_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln702_2_fu_368_p2 <= "0" when (and_ln702_1_fu_363_p2 = ap_const_lv86_0) else "1";
    icmp_ln702_3_fu_413_p2 <= "1" when (signed(add_ln702_fu_327_p2) > signed(ap_const_lv7_0)) else "0";
    icmp_ln702_fu_277_p2 <= "1" when (grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out = ap_const_lv86_0) else "0";
    lshr_ln695_fu_259_p2 <= std_logic_vector(shift_right(unsigned(zext_ln681_fu_223_p1),to_integer(unsigned('0' & zext_ln695_fu_249_p1(31-1 downto 0)))));
    lshr_ln702_1_fu_477_p4 <= add_ln702_2_fu_471_p2(63 downto 1);
    lshr_ln702_2_fu_357_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv86_3FFFFFFFFFFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln702_fu_353_p1(31-1 downto 0)))));
    lshr_ln702_fu_436_p2 <= std_logic_vector(shift_right(unsigned(select_ln702_reg_586),to_integer(unsigned('0' & zext_ln702_1_fu_432_p1(31-1 downto 0)))));
    or_ln702_fu_407_p2 <= (phi_ln702_fu_374_p2 or and_ln702_fu_401_p2);
    phi_ln702_fu_374_p2 <= (icmp_ln702_2_fu_368_p2 and icmp_ln702_1_fu_342_p2);
    select_ln695_fu_241_p3 <= 
        sub_ln695_fu_235_p2 when (tmp_fu_227_p3(0) = '1') else 
        trunc_ln688_fu_190_p1;
    select_ln702_1_fu_461_p3 <= 
        trunc_ln702_2_fu_453_p1 when (icmp_ln702_3_reg_612(0) = '1') else 
        trunc_ln702_3_fu_457_p1;
    select_ln702_2_fu_499_p3 <= 
        ap_const_lv11_3FF when (tmp_6_fu_491_p3(0) = '1') else 
        ap_const_lv11_3FE;
    select_ln702_fu_297_p3 <= 
        sub_ln702_fu_291_p2 when (tmp_1_fu_283_p3(0) = '1') else 
        grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out;
        sext_ln702_1_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln702_2_reg_622),32));

        sext_ln702_2_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln702_3_fu_507_p2),11));

        sext_ln702_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln702_1_reg_617),32));

    shl_ln695_fu_253_p2 <= std_logic_vector(shift_left(unsigned(zext_ln681_fu_223_p1),to_integer(unsigned('0' & zext_ln695_fu_249_p1(31-1 downto 0)))));
    shl_ln702_fu_448_p2 <= std_logic_vector(shift_left(unsigned(select_ln702_reg_586),to_integer(unsigned('0' & zext_ln702_4_fu_444_p1(31-1 downto 0)))));
    sub_ln695_fu_235_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(trunc_ln688_fu_190_p1));
    sub_ln702_1_fu_321_p2 <= std_logic_vector(signed(ap_const_lv7_56) - signed(trunc_ln702_fu_313_p1));
    sub_ln702_2_fu_424_p2 <= std_logic_vector(unsigned(ap_const_lv7_36) - unsigned(sub_ln702_1_reg_599));
    sub_ln702_3_fu_507_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) - unsigned(trunc_ln702_1_reg_594));
    sub_ln702_4_fu_348_p2 <= std_logic_vector(unsigned(ap_const_lv7_C) - unsigned(sub_ln702_1_reg_599));
    sub_ln702_fu_291_p2 <= std_logic_vector(unsigned(ap_const_lv86_0) - unsigned(grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out));
    tmp_1_fu_283_p3 <= grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out(85 downto 85);
    tmp_2_fu_332_p4 <= add_ln702_fu_327_p2(6 downto 1);
    tmp_3_fu_305_p1 <= 
        sub_ln702_fu_291_p2 when (tmp_1_fu_283_p3(0) = '1') else 
        grp_atan2_generic_double_Pipeline_1_fu_118_z_2_out;
    tmp_4_fu_380_p3 <= add_ln702_fu_327_p2(6 downto 6);
    tmp_6_fu_491_p3 <= add_ln702_2_fu_471_p2(54 downto 54);
    tmp_9_fu_522_p3 <= (tmp_1_reg_581 & add_ln702_3_fu_516_p2);
    tmp_fu_227_p3 <= d_exp_fu_184_p2(11 downto 11);
    trunc_ln505_1_fu_209_p1 <= data_1_fu_146_p1(52 - 1 downto 0);
    trunc_ln505_fu_194_p1 <= data_fu_134_p1(52 - 1 downto 0);
    trunc_ln688_fu_190_p1 <= d_exp_fu_184_p2(11 - 1 downto 0);
    trunc_ln702_1_fu_317_p1 <= tmp_3_fu_305_p3(8 - 1 downto 0);
    trunc_ln702_2_fu_453_p1 <= lshr_ln702_fu_436_p2(64 - 1 downto 0);
    trunc_ln702_3_fu_457_p1 <= shl_ln702_fu_448_p2(64 - 1 downto 0);
    trunc_ln702_fu_313_p1 <= tmp_3_fu_305_p3(7 - 1 downto 0);
    x_fu_198_p4 <= ((ap_const_lv1_1 & trunc_ln505_fu_194_p1) & ap_const_lv33_0);
    xor_ln702_fu_388_p2 <= (tmp_4_fu_380_p3 xor ap_const_lv1_1);
    y_1_fu_265_p3 <= 
        shl_ln695_fu_253_p2 when (tmp_fu_227_p3(0) = '1') else 
        lshr_ln695_fu_259_p2;
    y_fu_213_p4 <= ((ap_const_lv1_1 & trunc_ln505_1_fu_209_p1) & ap_const_lv33_0);
    zext_ln655_1_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(fps_x_exp_fu_138_p3),12));
    zext_ln655_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(fps_y_exp_fu_150_p3),12));
    zext_ln681_fu_223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_213_p4),89));
    zext_ln695_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln695_fu_241_p3),89));
    zext_ln702_1_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln702_fu_429_p1),86));
    zext_ln702_2_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln702_reg_607),64));
    zext_ln702_3_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln702_1_fu_477_p4),64));
    zext_ln702_4_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln702_1_fu_441_p1),86));
    zext_ln702_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln702_4_fu_348_p2),86));
end behav;
