-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity equalStep_baseline_atan2_cordic_double_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    y_in : IN STD_LOGIC_VECTOR (63 downto 0);
    x_in : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_131_p_din0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_131_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_131_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_131_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_131_p_ce : OUT STD_LOGIC );
end;


architecture behav of equalStep_baseline_atan2_cordic_double_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_3FE921FB54442D18 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111101001001000011111101101010100010001000010110100011000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_C002D97C7F3321D2 : STD_LOGIC_VECTOR (63 downto 0) := "1100000000000010110110010111110001111111001100110010000111010010";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv64_4002D97C7F3321D2 : STD_LOGIC_VECTOR (63 downto 0) := "0100000000000010110110010111110001111111001100110010000111010010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv64_BFE921FB54442D18 : STD_LOGIC_VECTOR (63 downto 0) := "1011111111101001001000011111101101010100010001000010110100011000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv64_C00921FB54442D18 : STD_LOGIC_VECTOR (63 downto 0) := "1100000000001001001000011111101101010100010001000010110100011000";
    constant ap_const_lv64_400921FB54442D18 : STD_LOGIC_VECTOR (63 downto 0) := "0100000000001001001000011111101101010100010001000010110100011000";
    constant ap_const_lv64_8000000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "1000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv64_7FFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "0111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_3FF921FB54442D18 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111111001001000011111101101010100010001000010110100011000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_3F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000111111";
    constant ap_const_lv64_BFF921FB54442D18 : STD_LOGIC_VECTOR (63 downto 0) := "1011111111111001001000011111101101010100010001000010110100011000";
    constant ap_const_lv63_3FF921FB54442D18 : STD_LOGIC_VECTOR (62 downto 0) := "011111111111001001000011111101101010100010001000010110100011000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_400921FB54442D18 : STD_LOGIC_VECTOR (62 downto 0) := "100000000001001001000011111101101010100010001000010110100011000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal fpsy_sign_fu_218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal fpsy_sign_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_579 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_583 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln733_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln733_reg_587 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln733_1_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln733_1_reg_591 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln733_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln733_reg_596 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln737_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln737_reg_600 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln737_1_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln737_1_reg_604 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln737_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln737_reg_609 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_310_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_reg_613 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln18_2_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_2_reg_618 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_3_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_3_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal a_reg_626 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_fu_352_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_reg_633 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln717_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln717_reg_643 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln717_1_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln717_1_reg_648 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_atan2_generic_double_s_fu_162_ap_return : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_reg_656 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_2_reg_661 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal d_reg_671 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal bitcast_ln793_1_fu_454_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln780_fu_492_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal bitcast_ln497_5_fu_506_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal bitcast_ln497_4_fu_517_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal bitcast_ln497_3_fu_528_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal bitcast_ln497_2_fu_539_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal bitcast_ln497_1_fu_550_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal bitcast_ln497_fu_561_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal grp_atan2_generic_double_s_fu_162_ap_start : STD_LOGIC;
    signal grp_atan2_generic_double_s_fu_162_ap_done : STD_LOGIC;
    signal grp_atan2_generic_double_s_fu_162_ap_idle : STD_LOGIC;
    signal grp_atan2_generic_double_s_fu_162_ap_ready : STD_LOGIC;
    signal grp_atan2_generic_double_s_fu_162_y_in : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_atan2_generic_double_s_fu_162_x_in : STD_LOGIC_VECTOR (63 downto 0);
    signal c_reg_84 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln715_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_UnifiedRetVal_phi_fu_110_p40 : STD_LOGIC_VECTOR (63 downto 0);
    signal UnifiedRetVal_reg_98 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln797_1_fu_487_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_atan2_generic_double_s_fu_162_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_170_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_170_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_177_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_177_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_fu_190_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_2_fu_214_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal fpsy_exp_fu_226_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal fpsy_sig_fu_234_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln18_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_1_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fpsx_exp_fu_202_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal fpsx_sig_fu_210_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln18_2_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_3_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fpsx_sign_fu_194_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_6_fu_331_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln479_fu_335_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_7_fu_344_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln479_1_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_363_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_373_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal or_ln717_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln717_1_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln717_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln793_fu_424_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bit_sel_fu_428_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln793_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln793_fu_442_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal xor_ln1_fu_446_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln797_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bit_sel1_fu_461_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln797_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln797_fu_475_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal xor_ln_fu_479_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_5_fu_499_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_4_fu_510_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_3_fu_521_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_2_fu_532_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_1_fu_543_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_fu_554_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln717_1_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component equalStep_baseline_atan2_generic_double_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y_in : IN STD_LOGIC_VECTOR (63 downto 0);
        x_in : IN STD_LOGIC_VECTOR (63 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component equalStep_baseline_dadddsub_64ns_64ns_64_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component equalStep_baseline_dcmp_64ns_64ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_atan2_generic_double_s_fu_162 : component equalStep_baseline_atan2_generic_double_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_atan2_generic_double_s_fu_162_ap_start,
        ap_done => grp_atan2_generic_double_s_fu_162_ap_done,
        ap_idle => grp_atan2_generic_double_s_fu_162_ap_idle,
        ap_ready => grp_atan2_generic_double_s_fu_162_ap_ready,
        y_in => grp_atan2_generic_double_s_fu_162_y_in,
        x_in => grp_atan2_generic_double_s_fu_162_x_in,
        ap_return => grp_atan2_generic_double_s_fu_162_ap_return);

    dcmp_64ns_64ns_1_2_no_dsp_1_U25 : component equalStep_baseline_dcmp_64ns_64ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_177_p0,
        din1 => grp_fu_177_p1,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_177_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv64_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                    ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_110_p40;
                end if; 
            end if;
        end if;
    end process;


    grp_atan2_generic_double_s_fu_162_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_atan2_generic_double_s_fu_162_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_atan2_generic_double_s_fu_162_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_atan2_generic_double_s_fu_162_ap_ready = ap_const_logic_1)) then 
                    grp_atan2_generic_double_s_fu_162_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    UnifiedRetVal_reg_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                UnifiedRetVal_reg_98 <= bitcast_ln497_5_fu_506_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                UnifiedRetVal_reg_98 <= bitcast_ln497_4_fu_517_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                UnifiedRetVal_reg_98 <= bitcast_ln497_3_fu_528_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
                UnifiedRetVal_reg_98 <= bitcast_ln497_2_fu_539_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
                UnifiedRetVal_reg_98 <= bitcast_ln497_1_fu_550_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                UnifiedRetVal_reg_98 <= bitcast_ln497_fu_561_p1;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv1_1 = and_ln18_1_fu_268_p2) or (ap_const_lv1_1 = and_ln18_fu_250_p2)))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_7FFFFFFFFFFFFFFF;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                UnifiedRetVal_reg_98 <= select_ln780_fu_492_p3;
            elsif (((tmp_1_reg_613 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                UnifiedRetVal_reg_98 <= grp_fu_131_p_dout0;
            elsif (((tmp_1_reg_613 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                UnifiedRetVal_reg_98 <= c_reg_84;
            elsif (((tmp_1_reg_613 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                UnifiedRetVal_reg_98 <= bitcast_ln793_1_fu_454_p1;
            elsif (((tmp_1_reg_613 = ap_const_lv2_3) and (icmp_ln737_reg_600 = ap_const_lv1_0) and (icmp_ln733_reg_587 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18) and (ap_const_lv1_0 = and_ln18_3_reg_622) and (ap_const_lv1_0 = and_ln18_2_reg_618) and (ap_const_lv1_0 = and_ln737_reg_609) and (ap_const_lv1_0 = and_ln733_reg_596) and (ap_const_lv1_0 = and_ln18_1_reg_583) and (ap_const_lv1_0 = and_ln18_reg_579))) then 
                UnifiedRetVal_reg_98 <= bitcast_ln797_1_fu_487_p1;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_0) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_0;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_1) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_8000000000000000;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_2) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_400921FB54442D18;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_3) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_C00921FB54442D18;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_0) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_3_fu_325_p2) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_3FE921FB54442D18;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_1) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_3_fu_325_p2) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_BFE921FB54442D18;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_2) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_3_fu_325_p2) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_4002D97C7F3321D2;
            elsif (((tmp_1_fu_310_p3 = ap_const_lv2_3) and (icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_3_fu_325_p2) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                UnifiedRetVal_reg_98 <= ap_const_lv64_C002D97C7F3321D2;
            end if; 
        end if;
    end process;

    c_reg_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln715_fu_357_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then 
                c_reg_84 <= ap_const_lv64_3FE921FB54442D18;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                c_reg_84 <= tmp_3_reg_656;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                c_reg_84 <= grp_fu_131_p_dout0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    a_reg_626(62 downto 0) <= a_fu_339_p1(62 downto 0);
                and_ln18_1_reg_583 <= and_ln18_1_fu_268_p2;
                and_ln18_2_reg_618 <= and_ln18_2_fu_319_p2;
                and_ln18_3_reg_622 <= and_ln18_3_fu_325_p2;
                and_ln18_reg_579 <= and_ln18_fu_250_p2;
                and_ln733_reg_596 <= and_ln733_fu_286_p2;
                and_ln737_reg_609 <= and_ln737_fu_304_p2;
                    b_reg_633(62 downto 0) <= b_fu_352_p1(62 downto 0);
                fpsy_sign_reg_568 <= data_2_fu_214_p1(63 downto 63);
                icmp_ln717_1_reg_648 <= icmp_ln717_1_fu_389_p2;
                icmp_ln717_reg_643 <= icmp_ln717_fu_383_p2;
                icmp_ln733_1_reg_591 <= icmp_ln733_1_fu_280_p2;
                icmp_ln733_reg_587 <= icmp_ln733_fu_274_p2;
                icmp_ln737_1_reg_604 <= icmp_ln737_1_fu_298_p2;
                icmp_ln737_reg_600 <= icmp_ln737_fu_292_p2;
                tmp_1_reg_613 <= tmp_1_fu_310_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                d_reg_671 <= grp_fu_131_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                tmp_2_reg_661 <= grp_atan2_generic_double_s_fu_162_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_3_reg_656 <= grp_atan2_generic_double_s_fu_162_ap_return;
            end if;
        end if;
    end process;
    a_reg_626(63) <= '0';
    b_reg_633(63) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, and_ln18_fu_250_p2, and_ln18_1_fu_268_p2, icmp_ln733_fu_274_p2, and_ln733_fu_286_p2, icmp_ln737_fu_292_p2, and_ln737_fu_304_p2, and_ln18_2_fu_319_p2, and_ln18_3_fu_325_p2, ap_CS_fsm_state4, ap_CS_fsm_state7, grp_atan2_generic_double_s_fu_162_ap_done, icmp_ln715_fu_357_p2, fpsx_sign_fu_194_p3, ap_CS_fsm_state2, and_ln717_1_fu_409_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((fpsx_sign_fu_194_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                elsif (((fpsx_sign_fu_194_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state24;
                elsif (((icmp_ln733_fu_274_p2 = ap_const_lv1_1) and (fpsx_sign_fu_194_p3 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                elsif (((icmp_ln733_fu_274_p2 = ap_const_lv1_1) and (fpsx_sign_fu_194_p3 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv1_1 = and_ln18_fu_250_p2) or ((ap_const_lv1_1 = and_ln18_1_fu_268_p2) or ((icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                elsif (((icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln715_fu_357_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                elsif (((icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln715_fu_357_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln737_fu_292_p2 = ap_const_lv1_0) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln18_3_fu_325_p2) and (ap_const_lv1_0 = and_ln18_2_fu_319_p2) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                elsif (((icmp_ln737_fu_292_p2 = ap_const_lv1_1) and (icmp_ln733_fu_274_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_0 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln737_fu_304_p2) and (ap_const_lv1_0 = and_ln733_fu_286_p2) and (ap_const_lv1_0 = and_ln18_1_fu_268_p2) and (ap_const_lv1_0 = and_ln18_fu_250_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv1_1 = and_ln717_1_fu_409_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_atan2_generic_double_s_fu_162_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_atan2_generic_double_s_fu_162_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    a_fu_339_p1 <= zext_ln479_fu_335_p1;
    and_ln18_1_fu_268_p2 <= (icmp_ln18_3_fu_262_p2 and icmp_ln18_2_fu_256_p2);
    and_ln18_2_fu_319_p2 <= (icmp_ln737_1_fu_298_p2 and icmp_ln18_2_fu_256_p2);
    and_ln18_3_fu_325_p2 <= (icmp_ln733_1_fu_280_p2 and icmp_ln18_fu_238_p2);
    and_ln18_fu_250_p2 <= (icmp_ln18_fu_238_p2 and icmp_ln18_1_fu_244_p2);
    and_ln717_1_fu_409_p2 <= (grp_fu_177_p2 and and_ln717_fu_403_p2);
    and_ln717_fu_403_p2 <= (or_ln717_fu_395_p2 and or_ln717_1_fu_399_p2);
    and_ln733_fu_286_p2 <= (icmp_ln733_fu_274_p2 and icmp_ln733_1_fu_280_p2);
    and_ln737_fu_304_p2 <= (icmp_ln737_fu_292_p2 and icmp_ln737_1_fu_298_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_atan2_generic_double_s_fu_162_ap_done)
    begin
        if ((grp_atan2_generic_double_s_fu_162_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_atan2_generic_double_s_fu_162_ap_done)
    begin
        if ((grp_atan2_generic_double_s_fu_162_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_UnifiedRetVal_phi_fu_110_p40_assign_proc : process(and_ln18_reg_579, and_ln18_1_reg_583, icmp_ln733_reg_587, and_ln733_reg_596, icmp_ln737_reg_600, and_ln737_reg_609, tmp_1_reg_613, and_ln18_2_reg_618, and_ln18_3_reg_622, UnifiedRetVal_reg_98, bitcast_ln797_1_fu_487_p1, ap_CS_fsm_state18)
    begin
        if (((tmp_1_reg_613 = ap_const_lv2_3) and (icmp_ln737_reg_600 = ap_const_lv1_0) and (icmp_ln733_reg_587 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18) and (ap_const_lv1_0 = and_ln18_3_reg_622) and (ap_const_lv1_0 = and_ln18_2_reg_618) and (ap_const_lv1_0 = and_ln737_reg_609) and (ap_const_lv1_0 = and_ln733_reg_596) and (ap_const_lv1_0 = and_ln18_1_reg_583) and (ap_const_lv1_0 = and_ln18_reg_579))) then 
            ap_phi_mux_UnifiedRetVal_phi_fu_110_p40 <= bitcast_ln797_1_fu_487_p1;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_110_p40 <= UnifiedRetVal_reg_98;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_UnifiedRetVal_phi_fu_110_p40, ap_CS_fsm_state18, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_110_p40;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    b_fu_352_p1 <= zext_ln479_1_fu_348_p1;
    bit_sel1_fu_461_p3 <= bitcast_ln797_fu_458_p1(63 downto 63);
    bit_sel_fu_428_p3 <= bitcast_ln793_fu_424_p1(63 downto 63);
    bitcast_ln497_1_fu_550_p1 <= t_1_fu_543_p3;
    bitcast_ln497_2_fu_539_p1 <= t_2_fu_532_p3;
    bitcast_ln497_3_fu_528_p1 <= t_3_fu_521_p3;
    bitcast_ln497_4_fu_517_p1 <= t_4_fu_510_p3;
    bitcast_ln497_5_fu_506_p1 <= t_5_fu_499_p3;
    bitcast_ln497_fu_561_p1 <= t_fu_554_p3;
    bitcast_ln793_1_fu_454_p1 <= xor_ln1_fu_446_p3;
    bitcast_ln793_fu_424_p1 <= c_reg_84;
    bitcast_ln797_1_fu_487_p1 <= xor_ln_fu_479_p3;
    bitcast_ln797_fu_458_p1 <= d_reg_671;
    data_2_fu_214_p1 <= y_in;
    data_fu_190_p1 <= x_in;
    fpsx_exp_fu_202_p3 <= data_fu_190_p1(62 downto 52);
    fpsx_sig_fu_210_p1 <= data_fu_190_p1(52 - 1 downto 0);
    fpsx_sign_fu_194_p3 <= data_fu_190_p1(63 downto 63);
    fpsy_exp_fu_226_p3 <= data_2_fu_214_p1(62 downto 52);
    fpsy_sig_fu_234_p1 <= data_2_fu_214_p1(52 - 1 downto 0);
    fpsy_sign_fu_218_p3 <= data_2_fu_214_p1(63 downto 63);
    grp_atan2_generic_double_s_fu_162_ap_start <= grp_atan2_generic_double_s_fu_162_ap_start_reg;

    grp_atan2_generic_double_s_fu_162_x_in_assign_proc : process(a_reg_626, b_reg_633, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_atan2_generic_double_s_fu_162_x_in <= a_reg_626;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_atan2_generic_double_s_fu_162_x_in <= b_reg_633;
        else 
            grp_atan2_generic_double_s_fu_162_x_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_atan2_generic_double_s_fu_162_y_in_assign_proc : process(a_reg_626, b_reg_633, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_atan2_generic_double_s_fu_162_y_in <= b_reg_633;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_atan2_generic_double_s_fu_162_y_in <= a_reg_626;
        else 
            grp_atan2_generic_double_s_fu_162_y_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_131_p_ce <= ap_const_logic_1;
    grp_fu_131_p_din0 <= grp_fu_170_p0;
    grp_fu_131_p_din1 <= grp_fu_170_p1;
    grp_fu_131_p_opcode <= ap_const_lv2_1(1 - 1 downto 0);

    grp_fu_170_p0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_170_p0 <= ap_const_lv64_400921FB54442D18;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_170_p0 <= ap_const_lv64_3FF921FB54442D18;
        else 
            grp_fu_170_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_170_p1_assign_proc : process(tmp_2_reg_661, c_reg_84, ap_CS_fsm_state8, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_170_p1 <= c_reg_84;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_170_p1 <= tmp_2_reg_661;
        else 
            grp_fu_170_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_177_p0 <= zext_ln479_fu_335_p1;
    grp_fu_177_p1 <= zext_ln479_1_fu_348_p1;
    icmp_ln18_1_fu_244_p2 <= "0" when (fpsy_sig_fu_234_p1 = ap_const_lv52_0) else "1";
    icmp_ln18_2_fu_256_p2 <= "1" when (fpsx_exp_fu_202_p3 = ap_const_lv11_7FF) else "0";
    icmp_ln18_3_fu_262_p2 <= "0" when (fpsx_sig_fu_210_p1 = ap_const_lv52_0) else "1";
    icmp_ln18_fu_238_p2 <= "1" when (fpsy_exp_fu_226_p3 = ap_const_lv11_7FF) else "0";
    icmp_ln715_fu_357_p2 <= "1" when (t_7_fu_344_p1 = t_6_fu_331_p1) else "0";
    icmp_ln717_1_fu_389_p2 <= "0" when (tmp_5_fu_373_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln717_fu_383_p2 <= "0" when (tmp_fu_363_p4 = ap_const_lv11_7FF) else "1";
    icmp_ln733_1_fu_280_p2 <= "1" when (fpsy_sig_fu_234_p1 = ap_const_lv52_0) else "0";
    icmp_ln733_fu_274_p2 <= "1" when (fpsy_exp_fu_226_p3 = ap_const_lv11_0) else "0";
    icmp_ln737_1_fu_298_p2 <= "1" when (fpsx_sig_fu_210_p1 = ap_const_lv52_0) else "0";
    icmp_ln737_fu_292_p2 <= "1" when (fpsx_exp_fu_202_p3 = ap_const_lv11_0) else "0";
    or_ln717_1_fu_399_p2 <= (icmp_ln737_1_reg_604 or icmp_ln717_1_reg_648);
    or_ln717_fu_395_p2 <= (icmp_ln733_1_reg_591 or icmp_ln717_reg_643);
    select_ln780_fu_492_p3 <= 
        ap_const_lv64_BFF921FB54442D18 when (fpsy_sign_reg_568(0) = '1') else 
        ap_const_lv64_3FF921FB54442D18;
    t_1_fu_543_p3 <= (fpsy_sign_reg_568 & ap_const_lv63_0);
    t_2_fu_532_p3 <= (fpsy_sign_reg_568 & ap_const_lv63_3FF921FB54442D18);
    t_3_fu_521_p3 <= (fpsy_sign_reg_568 & ap_const_lv63_400921FB54442D18);
    t_4_fu_510_p3 <= (fpsy_sign_reg_568 & ap_const_lv63_0);
    t_5_fu_499_p3 <= (fpsy_sign_reg_568 & ap_const_lv63_3FF921FB54442D18);
    t_6_fu_331_p1 <= data_2_fu_214_p1(63 - 1 downto 0);
    t_7_fu_344_p1 <= data_fu_190_p1(63 - 1 downto 0);
    t_fu_554_p3 <= (fpsy_sign_reg_568 & ap_const_lv63_400921FB54442D18);
    tmp_1_fu_310_p3 <= (fpsx_sign_fu_194_p3 & fpsy_sign_fu_218_p3);
    tmp_5_fu_373_p4 <= data_fu_190_p1(62 downto 52);
    tmp_fu_363_p4 <= data_2_fu_214_p1(62 downto 52);
    trunc_ln793_fu_442_p1 <= bitcast_ln793_fu_424_p1(63 - 1 downto 0);
    trunc_ln797_fu_475_p1 <= bitcast_ln797_fu_458_p1(63 - 1 downto 0);
    xor_ln1_fu_446_p3 <= (xor_ln793_fu_436_p2 & trunc_ln793_fu_442_p1);
    xor_ln793_fu_436_p2 <= (bit_sel_fu_428_p3 xor ap_const_lv1_1);
    xor_ln797_fu_469_p2 <= (bit_sel1_fu_461_p3 xor ap_const_lv1_1);
    xor_ln_fu_479_p3 <= (xor_ln797_fu_469_p2 & trunc_ln797_fu_475_p1);
    zext_ln479_1_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_7_fu_344_p1),64));
    zext_ln479_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_6_fu_331_p1),64));
end behav;
