-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity equalStep_baseline_bitselect_1ns_81ns_7ns_1_1_1 is
generic (
    ADDRWIDTH : INTEGER := 7;
    DATAWIDTH : INTEGER := 81
);
port (

    sel   : in std_logic_vector (ADDRWIDTH-1 downto 0);
    din   : in std_logic_vector (DATAWIDTH-1 downto 0);
    dout  : out std_logic_vector (0 downto 0)
);
end entity;

architecture behav of equalStep_baseline_bitselect_1ns_81ns_7ns_1_1_1 is
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of behav: architecture is "yes";
    signal dout_tmp : std_logic_vector (0 downto 0);

    signal sel_integer : integer;
begin
    sel_integer <= to_integer(unsigned(sel));
    process(din,sel_integer) is
    begin
        case sel_integer is
            
            when 0 =>
                dout_tmp(0) <= din(0);
            
            when 1 =>
                dout_tmp(0) <= din(1);
            
            when 2 =>
                dout_tmp(0) <= din(2);
            
            when 3 =>
                dout_tmp(0) <= din(3);
            
            when 4 =>
                dout_tmp(0) <= din(4);
            
            when 5 =>
                dout_tmp(0) <= din(5);
            
            when 6 =>
                dout_tmp(0) <= din(6);
            
            when 7 =>
                dout_tmp(0) <= din(7);
            
            when 8 =>
                dout_tmp(0) <= din(8);
            
            when 9 =>
                dout_tmp(0) <= din(9);
            
            when 10 =>
                dout_tmp(0) <= din(10);
            
            when 11 =>
                dout_tmp(0) <= din(11);
            
            when 12 =>
                dout_tmp(0) <= din(12);
            
            when 13 =>
                dout_tmp(0) <= din(13);
            
            when 14 =>
                dout_tmp(0) <= din(14);
            
            when 15 =>
                dout_tmp(0) <= din(15);
            
            when 16 =>
                dout_tmp(0) <= din(16);
            
            when 17 =>
                dout_tmp(0) <= din(17);
            
            when 18 =>
                dout_tmp(0) <= din(18);
            
            when 19 =>
                dout_tmp(0) <= din(19);
            
            when 20 =>
                dout_tmp(0) <= din(20);
            
            when 21 =>
                dout_tmp(0) <= din(21);
            
            when 22 =>
                dout_tmp(0) <= din(22);
            
            when 23 =>
                dout_tmp(0) <= din(23);
            
            when 24 =>
                dout_tmp(0) <= din(24);
            
            when 25 =>
                dout_tmp(0) <= din(25);
            
            when 26 =>
                dout_tmp(0) <= din(26);
            
            when 27 =>
                dout_tmp(0) <= din(27);
            
            when 28 =>
                dout_tmp(0) <= din(28);
            
            when 29 =>
                dout_tmp(0) <= din(29);
            
            when 30 =>
                dout_tmp(0) <= din(30);
            
            when 31 =>
                dout_tmp(0) <= din(31);
            
            when 32 =>
                dout_tmp(0) <= din(32);
            
            when 33 =>
                dout_tmp(0) <= din(33);
            
            when 34 =>
                dout_tmp(0) <= din(34);
            
            when 35 =>
                dout_tmp(0) <= din(35);
            
            when 36 =>
                dout_tmp(0) <= din(36);
            
            when 37 =>
                dout_tmp(0) <= din(37);
            
            when 38 =>
                dout_tmp(0) <= din(38);
            
            when 39 =>
                dout_tmp(0) <= din(39);
            
            when 40 =>
                dout_tmp(0) <= din(40);
            
            when 41 =>
                dout_tmp(0) <= din(41);
            
            when 42 =>
                dout_tmp(0) <= din(42);
            
            when 43 =>
                dout_tmp(0) <= din(43);
            
            when 44 =>
                dout_tmp(0) <= din(44);
            
            when 45 =>
                dout_tmp(0) <= din(45);
            
            when 46 =>
                dout_tmp(0) <= din(46);
            
            when 47 =>
                dout_tmp(0) <= din(47);
            
            when 48 =>
                dout_tmp(0) <= din(48);
            
            when 49 =>
                dout_tmp(0) <= din(49);
            
            when 50 =>
                dout_tmp(0) <= din(50);
            
            when 51 =>
                dout_tmp(0) <= din(51);
            
            when 52 =>
                dout_tmp(0) <= din(52);
            
            when 53 =>
                dout_tmp(0) <= din(53);
            
            when 54 =>
                dout_tmp(0) <= din(54);
            
            when 55 =>
                dout_tmp(0) <= din(55);
            
            when 56 =>
                dout_tmp(0) <= din(56);
            
            when 57 =>
                dout_tmp(0) <= din(57);
            
            when 58 =>
                dout_tmp(0) <= din(58);
            
            when 59 =>
                dout_tmp(0) <= din(59);
            
            when 60 =>
                dout_tmp(0) <= din(60);
            
            when 61 =>
                dout_tmp(0) <= din(61);
            
            when 62 =>
                dout_tmp(0) <= din(62);
            
            when 63 =>
                dout_tmp(0) <= din(63);
            
            when 64 =>
                dout_tmp(0) <= din(64);
            
            when 65 =>
                dout_tmp(0) <= din(65);
            
            when 66 =>
                dout_tmp(0) <= din(66);
            
            when 67 =>
                dout_tmp(0) <= din(67);
            
            when 68 =>
                dout_tmp(0) <= din(68);
            
            when 69 =>
                dout_tmp(0) <= din(69);
            
            when 70 =>
                dout_tmp(0) <= din(70);
            
            when 71 =>
                dout_tmp(0) <= din(71);
            
            when 72 =>
                dout_tmp(0) <= din(72);
            
            when 73 =>
                dout_tmp(0) <= din(73);
            
            when 74 =>
                dout_tmp(0) <= din(74);
            
            when 75 =>
                dout_tmp(0) <= din(75);
            
            when 76 =>
                dout_tmp(0) <= din(76);
            
            when 77 =>
                dout_tmp(0) <= din(77);
            
            when 78 =>
                dout_tmp(0) <= din(78);
            
            when 79 =>
                dout_tmp(0) <= din(79);
            
            when 80 =>
                dout_tmp(0) <= din(80);
            
            when others => 
                dout_tmp(0) <= 'X';
        end case;
    end process;


    dout <= dout_tmp;




end architecture;
