-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
Library ieee;
use ieee.std_logic_1164.all;
use IEEE.numeric_std.all;

entity equalStep_baseline_ctlz_86_86_1_1 is
generic (
    din_WIDTH : INTEGER := 1;
    dout_WIDTH : INTEGER := 1);
port(

    din: in std_logic_vector(din_WIDTH - 1 downto 0);
    dout: out std_logic_vector(dout_WIDTH - 1 downto 0));
end entity;

architecture arch of equalStep_baseline_ctlz_86_86_1_1 is
    signal dout_tmp : std_logic_vector(dout_WIDTH - 1 downto 0);

begin

    dout <=  dout_tmp;


    
    process (din)
    begin 
        dout_tmp <= std_logic_vector(to_unsigned(86, dout_WIDTH));
        for i in 0 to 85 loop
            if din(85 - i) = '1' then
                dout_tmp <= std_logic_vector(to_unsigned(i, dout_WIDTH));
                exit;
            end if;
        end loop;
    end process;



end architecture;
