// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module equalStep_baseline_atan2_generic_double_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_1,
        zext_ln681,
        z_2_out,
        z_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [88:0] y_1;
input  [85:0] zext_ln681;
output  [85:0] z_2_out;
output   z_2_out_ap_vld;

reg ap_idle;
reg z_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln138_fu_139_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] cordic_ctab_table_128_address0;
wire   [125:0] cordic_ctab_table_128_q0;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] k_2_reg_331;
reg   [0:0] icmp_ln138_reg_336;
wire   [0:0] add_fu_167_p3;
reg   [0:0] add_reg_345;
wire   [84:0] b_2_fu_252_p2;
reg   [84:0] b_2_reg_350;
wire   [63:0] zext_ln138_fu_151_p1;
wire    ap_block_pp0_stage0;
reg   [88:0] a_fu_64;
wire   [88:0] x_fu_196_p3;
wire   [88:0] zext_ln681_cast_fu_112_p1;
wire    ap_loop_init;
reg   [88:0] a_1_fu_68;
wire   [88:0] y_fu_222_p3;
reg   [85:0] a_2_fu_72;
wire   [85:0] z_fu_286_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [6:0] k_fu_76;
wire   [6:0] add_ln138_fu_145_p2;
reg   [6:0] ap_sig_allocacmp_k_2;
wire    ap_block_pp0_stage0_01001;
reg    cordic_ctab_table_128_ce0_local;
wire   [88:0] zext_ln159_fu_175_p1;
wire   [88:0] y_s_fu_178_p2;
wire   [88:0] sub_ln101_fu_184_p2;
wire   [88:0] add_ln101_fu_190_p2;
wire   [88:0] x_s_fu_204_p2;
wire   [88:0] add_ln101_1_fu_216_p2;
wire   [88:0] sub_ln101_1_fu_210_p2;
wire   [0:0] tmp_fu_240_p3;
wire   [84:0] trunc_ln1_fu_230_p4;
wire   [84:0] zext_ln163_fu_248_p1;
wire   [85:0] zext_ln164_fu_271_p1;
wire   [85:0] sub_ln101_2_fu_274_p2;
wire   [85:0] add_ln101_2_fu_280_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 a_fu_64 = 89'd0;
#0 a_1_fu_68 = 89'd0;
#0 a_2_fu_72 = 86'd0;
#0 k_fu_76 = 7'd0;
#0 ap_done_reg = 1'b0;
end

equalStep_baseline_atan2_generic_double_Pipeline_1_cordic_ctab_table_128_ROM_AUTO_1R #(
    .DataWidth( 126 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
cordic_ctab_table_128_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cordic_ctab_table_128_address0),
    .ce0(cordic_ctab_table_128_ce0_local),
    .q0(cordic_ctab_table_128_q0)
);

equalStep_baseline_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            a_1_fu_68 <= y_1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            a_1_fu_68 <= y_fu_222_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            a_2_fu_72 <= 86'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            a_2_fu_72 <= z_fu_286_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            a_fu_64 <= zext_ln681_cast_fu_112_p1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            a_fu_64 <= x_fu_196_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln138_fu_139_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_76 <= add_ln138_fu_145_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_76 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_reg_345 <= a_1_fu_68[32'd88];
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        b_2_reg_350 <= b_2_fu_252_p2;
        icmp_ln138_reg_336 <= icmp_ln138_fu_139_p2;
        k_2_reg_331 <= ap_sig_allocacmp_k_2;
    end
end

always @ (*) begin
    if (((icmp_ln138_fu_139_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_k_2 = k_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cordic_ctab_table_128_ce0_local = 1'b1;
    end else begin
        cordic_ctab_table_128_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln138_reg_336 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        z_2_out_ap_vld = 1'b1;
    end else begin
        z_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_fu_167_p3 = a_1_fu_68[32'd88];

assign add_ln101_1_fu_216_p2 = (x_s_fu_204_p2 + a_1_fu_68);

assign add_ln101_2_fu_280_p2 = (zext_ln164_fu_271_p1 + a_2_fu_72);

assign add_ln101_fu_190_p2 = (y_s_fu_178_p2 + a_fu_64);

assign add_ln138_fu_145_p2 = (ap_sig_allocacmp_k_2 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_2_fu_252_p2 = (trunc_ln1_fu_230_p4 + zext_ln163_fu_248_p1);

assign cordic_ctab_table_128_address0 = zext_ln138_fu_151_p1;

assign icmp_ln138_fu_139_p2 = ((ap_sig_allocacmp_k_2 == 7'd88) ? 1'b1 : 1'b0);

assign sub_ln101_1_fu_210_p2 = (a_1_fu_68 - x_s_fu_204_p2);

assign sub_ln101_2_fu_274_p2 = (a_2_fu_72 - zext_ln164_fu_271_p1);

assign sub_ln101_fu_184_p2 = (a_fu_64 - y_s_fu_178_p2);

assign tmp_fu_240_p3 = cordic_ctab_table_128_q0[32'd40];

assign trunc_ln1_fu_230_p4 = {{cordic_ctab_table_128_q0[125:41]}};

assign x_fu_196_p3 = ((add_fu_167_p3[0:0] == 1'b1) ? sub_ln101_fu_184_p2 : add_ln101_fu_190_p2);

assign x_s_fu_204_p2 = $signed(a_fu_64) >>> zext_ln159_fu_175_p1;

assign y_fu_222_p3 = ((add_fu_167_p3[0:0] == 1'b1) ? add_ln101_1_fu_216_p2 : sub_ln101_1_fu_210_p2);

assign y_s_fu_178_p2 = $signed(a_1_fu_68) >>> zext_ln159_fu_175_p1;

assign z_2_out = a_2_fu_72;

assign z_fu_286_p3 = ((add_reg_345[0:0] == 1'b1) ? sub_ln101_2_fu_274_p2 : add_ln101_2_fu_280_p2);

assign zext_ln138_fu_151_p1 = ap_sig_allocacmp_k_2;

assign zext_ln159_fu_175_p1 = k_2_reg_331;

assign zext_ln163_fu_248_p1 = tmp_fu_240_p3;

assign zext_ln164_fu_271_p1 = b_2_reg_350;

assign zext_ln681_cast_fu_112_p1 = zext_ln681;

endmodule //equalStep_baseline_atan2_generic_double_Pipeline_1
