// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module equalStep_baseline_atan2_cordic_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_in,
        x_in,
        ap_return,
        grp_fu_131_p_din0,
        grp_fu_131_p_din1,
        grp_fu_131_p_opcode,
        grp_fu_131_p_dout0,
        grp_fu_131_p_ce
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] y_in;
input  [63:0] x_in;
output  [63:0] ap_return;
output  [63:0] grp_fu_131_p_din0;
output  [63:0] grp_fu_131_p_din1;
output  [0:0] grp_fu_131_p_opcode;
input  [63:0] grp_fu_131_p_dout0;
output   grp_fu_131_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] fpsy_sign_fu_218_p3;
reg   [0:0] fpsy_sign_reg_568;
wire   [0:0] and_ln18_fu_250_p2;
reg   [0:0] and_ln18_reg_579;
wire   [0:0] and_ln18_1_fu_268_p2;
reg   [0:0] and_ln18_1_reg_583;
wire   [0:0] icmp_ln733_fu_274_p2;
reg   [0:0] icmp_ln733_reg_587;
wire   [0:0] icmp_ln733_1_fu_280_p2;
reg   [0:0] icmp_ln733_1_reg_591;
wire   [0:0] and_ln733_fu_286_p2;
reg   [0:0] and_ln733_reg_596;
wire   [0:0] icmp_ln737_fu_292_p2;
reg   [0:0] icmp_ln737_reg_600;
wire   [0:0] icmp_ln737_1_fu_298_p2;
reg   [0:0] icmp_ln737_1_reg_604;
wire   [0:0] and_ln737_fu_304_p2;
reg   [0:0] and_ln737_reg_609;
wire   [1:0] tmp_1_fu_310_p3;
reg   [1:0] tmp_1_reg_613;
wire   [0:0] and_ln18_2_fu_319_p2;
reg   [0:0] and_ln18_2_reg_618;
wire   [0:0] and_ln18_3_fu_325_p2;
reg   [0:0] and_ln18_3_reg_622;
wire   [63:0] a_fu_339_p1;
reg   [63:0] a_reg_626;
wire   [63:0] b_fu_352_p1;
reg   [63:0] b_reg_633;
wire   [0:0] icmp_ln717_fu_383_p2;
reg   [0:0] icmp_ln717_reg_643;
wire   [0:0] icmp_ln717_1_fu_389_p2;
reg   [0:0] icmp_ln717_1_reg_648;
wire   [63:0] grp_atan2_generic_double_s_fu_162_ap_return;
reg   [63:0] tmp_3_reg_656;
wire    ap_CS_fsm_state4;
reg   [63:0] tmp_2_reg_661;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state12;
reg   [63:0] d_reg_671;
wire    ap_CS_fsm_state17;
wire   [63:0] bitcast_ln793_1_fu_454_p1;
wire   [63:0] select_ln780_fu_492_p3;
wire    ap_CS_fsm_state19;
wire   [63:0] bitcast_ln497_5_fu_506_p1;
wire    ap_CS_fsm_state20;
wire   [63:0] bitcast_ln497_4_fu_517_p1;
wire    ap_CS_fsm_state21;
wire   [63:0] bitcast_ln497_3_fu_528_p1;
wire    ap_CS_fsm_state22;
wire   [63:0] bitcast_ln497_2_fu_539_p1;
wire    ap_CS_fsm_state23;
wire   [63:0] bitcast_ln497_1_fu_550_p1;
wire    ap_CS_fsm_state24;
wire   [63:0] bitcast_ln497_fu_561_p1;
wire    ap_CS_fsm_state25;
wire    grp_atan2_generic_double_s_fu_162_ap_start;
wire    grp_atan2_generic_double_s_fu_162_ap_done;
wire    grp_atan2_generic_double_s_fu_162_ap_idle;
wire    grp_atan2_generic_double_s_fu_162_ap_ready;
reg   [63:0] grp_atan2_generic_double_s_fu_162_y_in;
reg   [63:0] grp_atan2_generic_double_s_fu_162_x_in;
reg   [63:0] c_reg_84;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln715_fu_357_p2;
reg   [63:0] ap_phi_mux_UnifiedRetVal_phi_fu_110_p40;
reg   [63:0] UnifiedRetVal_reg_98;
wire   [63:0] bitcast_ln797_1_fu_487_p1;
wire    ap_CS_fsm_state18;
reg    grp_atan2_generic_double_s_fu_162_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state6;
reg   [63:0] grp_fu_170_p0;
reg   [63:0] grp_fu_170_p1;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state13;
wire   [63:0] grp_fu_177_p0;
wire   [63:0] grp_fu_177_p1;
wire   [63:0] data_fu_190_p1;
wire   [63:0] data_2_fu_214_p1;
wire   [10:0] fpsy_exp_fu_226_p3;
wire   [51:0] fpsy_sig_fu_234_p1;
wire   [0:0] icmp_ln18_fu_238_p2;
wire   [0:0] icmp_ln18_1_fu_244_p2;
wire   [10:0] fpsx_exp_fu_202_p3;
wire   [51:0] fpsx_sig_fu_210_p1;
wire   [0:0] icmp_ln18_2_fu_256_p2;
wire   [0:0] icmp_ln18_3_fu_262_p2;
wire   [0:0] fpsx_sign_fu_194_p3;
wire   [62:0] t_6_fu_331_p1;
wire   [63:0] zext_ln479_fu_335_p1;
wire   [62:0] t_7_fu_344_p1;
wire   [63:0] zext_ln479_1_fu_348_p1;
wire   [10:0] tmp_fu_363_p4;
wire   [10:0] tmp_5_fu_373_p4;
wire    ap_CS_fsm_state2;
wire   [0:0] or_ln717_fu_395_p2;
wire   [0:0] or_ln717_1_fu_399_p2;
wire   [0:0] and_ln717_fu_403_p2;
wire   [0:0] grp_fu_177_p2;
wire   [63:0] bitcast_ln793_fu_424_p1;
wire   [0:0] bit_sel_fu_428_p3;
wire   [0:0] xor_ln793_fu_436_p2;
wire   [62:0] trunc_ln793_fu_442_p1;
wire   [63:0] xor_ln1_fu_446_p3;
wire   [63:0] bitcast_ln797_fu_458_p1;
wire   [0:0] bit_sel1_fu_461_p3;
wire   [0:0] xor_ln797_fu_469_p2;
wire   [62:0] trunc_ln797_fu_475_p1;
wire   [63:0] xor_ln_fu_479_p3;
wire   [63:0] t_5_fu_499_p3;
wire   [63:0] t_4_fu_510_p3;
wire   [63:0] t_3_fu_521_p3;
wire   [63:0] t_2_fu_532_p3;
wire   [63:0] t_1_fu_543_p3;
wire   [63:0] t_fu_554_p3;
wire   [0:0] and_ln717_1_fu_409_p2;
reg   [63:0] ap_return_preg;
reg   [24:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 grp_atan2_generic_double_s_fu_162_ap_start_reg = 1'b0;
#0 ap_return_preg = 64'd0;
end

equalStep_baseline_atan2_generic_double_s grp_atan2_generic_double_s_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_atan2_generic_double_s_fu_162_ap_start),
    .ap_done(grp_atan2_generic_double_s_fu_162_ap_done),
    .ap_idle(grp_atan2_generic_double_s_fu_162_ap_idle),
    .ap_ready(grp_atan2_generic_double_s_fu_162_ap_ready),
    .y_in(grp_atan2_generic_double_s_fu_162_y_in),
    .x_in(grp_atan2_generic_double_s_fu_162_x_in),
    .ap_return(grp_atan2_generic_double_s_fu_162_ap_return)
);

equalStep_baseline_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_177_p0),
    .din1(grp_fu_177_p1),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_177_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_110_p40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_atan2_generic_double_s_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state3))) begin
            grp_atan2_generic_double_s_fu_162_ap_start_reg <= 1'b1;
        end else if ((grp_atan2_generic_double_s_fu_162_ap_ready == 1'b1)) begin
            grp_atan2_generic_double_s_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        UnifiedRetVal_reg_98 <= bitcast_ln497_5_fu_506_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        UnifiedRetVal_reg_98 <= bitcast_ln497_4_fu_517_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        UnifiedRetVal_reg_98 <= bitcast_ln497_3_fu_528_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        UnifiedRetVal_reg_98 <= bitcast_ln497_2_fu_539_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        UnifiedRetVal_reg_98 <= bitcast_ln497_1_fu_550_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        UnifiedRetVal_reg_98 <= bitcast_ln497_fu_561_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((1'd1 == and_ln18_1_fu_268_p2) | (1'd1 == and_ln18_fu_250_p2)))) begin
        UnifiedRetVal_reg_98 <= 64'd9223372036854775807;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        UnifiedRetVal_reg_98 <= select_ln780_fu_492_p3;
    end else if (((tmp_1_reg_613 == 2'd2) & (1'b1 == ap_CS_fsm_state17))) begin
        UnifiedRetVal_reg_98 <= grp_fu_131_p_dout0;
    end else if (((tmp_1_reg_613 == 2'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        UnifiedRetVal_reg_98 <= c_reg_84;
    end else if (((tmp_1_reg_613 == 2'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        UnifiedRetVal_reg_98 <= bitcast_ln793_1_fu_454_p1;
    end else if (((tmp_1_reg_613 == 2'd3) & (icmp_ln737_reg_600 == 1'd0) & (icmp_ln733_reg_587 == 1'd0) & (1'b1 == ap_CS_fsm_state18) & (1'd0 == and_ln18_3_reg_622) & (1'd0 == and_ln18_2_reg_618) & (1'd0 == and_ln737_reg_609) & (1'd0 == and_ln733_reg_596) & (1'd0 == and_ln18_1_reg_583) & (1'd0 == and_ln18_reg_579))) begin
        UnifiedRetVal_reg_98 <= bitcast_ln797_1_fu_487_p1;
    end else if (((tmp_1_fu_310_p3 == 2'd0) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd0;
    end else if (((tmp_1_fu_310_p3 == 2'd1) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd9223372036854775808;
    end else if (((tmp_1_fu_310_p3 == 2'd2) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd4614256656552045848;
    end else if (((tmp_1_fu_310_p3 == 2'd3) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd13837628693406821656;
    end else if (((tmp_1_fu_310_p3 == 2'd0) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_3_fu_325_p2) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd4605249457297304856;
    end else if (((tmp_1_fu_310_p3 == 2'd1) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_3_fu_325_p2) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd13828621494152080664;
    end else if (((tmp_1_fu_310_p3 == 2'd2) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_3_fu_325_p2) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd4612488097114038738;
    end else if (((tmp_1_fu_310_p3 == 2'd3) & (icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_3_fu_325_p2) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        UnifiedRetVal_reg_98 <= 64'd13835860133968814546;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln715_fu_357_p2 == 1'd1) & (1'd0 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
        c_reg_84 <= 64'd4605249457297304856;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        c_reg_84 <= tmp_3_reg_656;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        c_reg_84 <= grp_fu_131_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a_reg_626[62 : 0] <= a_fu_339_p1[62 : 0];
        and_ln18_1_reg_583 <= and_ln18_1_fu_268_p2;
        and_ln18_2_reg_618 <= and_ln18_2_fu_319_p2;
        and_ln18_3_reg_622 <= and_ln18_3_fu_325_p2;
        and_ln18_reg_579 <= and_ln18_fu_250_p2;
        and_ln733_reg_596 <= and_ln733_fu_286_p2;
        and_ln737_reg_609 <= and_ln737_fu_304_p2;
        b_reg_633[62 : 0] <= b_fu_352_p1[62 : 0];
        fpsy_sign_reg_568 <= data_2_fu_214_p1[32'd63];
        icmp_ln717_1_reg_648 <= icmp_ln717_1_fu_389_p2;
        icmp_ln717_reg_643 <= icmp_ln717_fu_383_p2;
        icmp_ln733_1_reg_591 <= icmp_ln733_1_fu_280_p2;
        icmp_ln733_reg_587 <= icmp_ln733_fu_274_p2;
        icmp_ln737_1_reg_604 <= icmp_ln737_1_fu_298_p2;
        icmp_ln737_reg_600 <= icmp_ln737_fu_292_p2;
        tmp_1_reg_613 <= tmp_1_fu_310_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        d_reg_671 <= grp_fu_131_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_2_reg_661 <= grp_atan2_generic_double_s_fu_162_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_3_reg_656 <= grp_atan2_generic_double_s_fu_162_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_atan2_generic_double_s_fu_162_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_atan2_generic_double_s_fu_162_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_613 == 2'd3) & (icmp_ln737_reg_600 == 1'd0) & (icmp_ln733_reg_587 == 1'd0) & (1'b1 == ap_CS_fsm_state18) & (1'd0 == and_ln18_3_reg_622) & (1'd0 == and_ln18_2_reg_618) & (1'd0 == and_ln737_reg_609) & (1'd0 == and_ln733_reg_596) & (1'd0 == and_ln18_1_reg_583) & (1'd0 == and_ln18_reg_579))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_110_p40 = bitcast_ln797_1_fu_487_p1;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_110_p40 = UnifiedRetVal_reg_98;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_110_p40;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_atan2_generic_double_s_fu_162_x_in = a_reg_626;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_atan2_generic_double_s_fu_162_x_in = b_reg_633;
    end else begin
        grp_atan2_generic_double_s_fu_162_x_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_atan2_generic_double_s_fu_162_y_in = b_reg_633;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_atan2_generic_double_s_fu_162_y_in = a_reg_626;
    end else begin
        grp_atan2_generic_double_s_fu_162_y_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_170_p0 = 64'd4614256656552045848;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_170_p0 = 64'd4609753056924675352;
    end else begin
        grp_fu_170_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_170_p1 = c_reg_84;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_170_p1 = tmp_2_reg_661;
    end else begin
        grp_fu_170_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((fpsx_sign_fu_194_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else if (((fpsx_sign_fu_194_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else if (((icmp_ln733_fu_274_p2 == 1'd1) & (fpsx_sign_fu_194_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else if (((icmp_ln733_fu_274_p2 == 1'd1) & (fpsx_sign_fu_194_p3 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((1'd1 == and_ln18_fu_250_p2) | ((1'd1 == and_ln18_1_fu_268_p2) | ((icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (1'd1 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2)))))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln715_fu_357_p2 == 1'd1) & (1'd0 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln715_fu_357_p2 == 1'd0) & (1'd0 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln737_fu_292_p2 == 1'd0) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln18_3_fu_325_p2) & (1'd0 == and_ln18_2_fu_319_p2) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else if (((icmp_ln737_fu_292_p2 == 1'd1) & (icmp_ln733_fu_274_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd0 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln737_fu_304_p2) & (1'd0 == and_ln733_fu_286_p2) & (1'd0 == and_ln18_1_fu_268_p2) & (1'd0 == and_ln18_fu_250_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln717_1_fu_409_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_atan2_generic_double_s_fu_162_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_atan2_generic_double_s_fu_162_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_339_p1 = zext_ln479_fu_335_p1;

assign and_ln18_1_fu_268_p2 = (icmp_ln18_3_fu_262_p2 & icmp_ln18_2_fu_256_p2);

assign and_ln18_2_fu_319_p2 = (icmp_ln737_1_fu_298_p2 & icmp_ln18_2_fu_256_p2);

assign and_ln18_3_fu_325_p2 = (icmp_ln733_1_fu_280_p2 & icmp_ln18_fu_238_p2);

assign and_ln18_fu_250_p2 = (icmp_ln18_fu_238_p2 & icmp_ln18_1_fu_244_p2);

assign and_ln717_1_fu_409_p2 = (grp_fu_177_p2 & and_ln717_fu_403_p2);

assign and_ln717_fu_403_p2 = (or_ln717_fu_395_p2 & or_ln717_1_fu_399_p2);

assign and_ln733_fu_286_p2 = (icmp_ln733_fu_274_p2 & icmp_ln733_1_fu_280_p2);

assign and_ln737_fu_304_p2 = (icmp_ln737_fu_292_p2 & icmp_ln737_1_fu_298_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign b_fu_352_p1 = zext_ln479_1_fu_348_p1;

assign bit_sel1_fu_461_p3 = bitcast_ln797_fu_458_p1[64'd63];

assign bit_sel_fu_428_p3 = bitcast_ln793_fu_424_p1[64'd63];

assign bitcast_ln497_1_fu_550_p1 = t_1_fu_543_p3;

assign bitcast_ln497_2_fu_539_p1 = t_2_fu_532_p3;

assign bitcast_ln497_3_fu_528_p1 = t_3_fu_521_p3;

assign bitcast_ln497_4_fu_517_p1 = t_4_fu_510_p3;

assign bitcast_ln497_5_fu_506_p1 = t_5_fu_499_p3;

assign bitcast_ln497_fu_561_p1 = t_fu_554_p3;

assign bitcast_ln793_1_fu_454_p1 = xor_ln1_fu_446_p3;

assign bitcast_ln793_fu_424_p1 = c_reg_84;

assign bitcast_ln797_1_fu_487_p1 = xor_ln_fu_479_p3;

assign bitcast_ln797_fu_458_p1 = d_reg_671;

assign data_2_fu_214_p1 = y_in;

assign data_fu_190_p1 = x_in;

assign fpsx_exp_fu_202_p3 = {{data_fu_190_p1[62:52]}};

assign fpsx_sig_fu_210_p1 = data_fu_190_p1[51:0];

assign fpsx_sign_fu_194_p3 = data_fu_190_p1[32'd63];

assign fpsy_exp_fu_226_p3 = {{data_2_fu_214_p1[62:52]}};

assign fpsy_sig_fu_234_p1 = data_2_fu_214_p1[51:0];

assign fpsy_sign_fu_218_p3 = data_2_fu_214_p1[32'd63];

assign grp_atan2_generic_double_s_fu_162_ap_start = grp_atan2_generic_double_s_fu_162_ap_start_reg;

assign grp_fu_131_p_ce = 1'b1;

assign grp_fu_131_p_din0 = grp_fu_170_p0;

assign grp_fu_131_p_din1 = grp_fu_170_p1;

assign grp_fu_131_p_opcode = 2'd1;

assign grp_fu_177_p0 = zext_ln479_fu_335_p1;

assign grp_fu_177_p1 = zext_ln479_1_fu_348_p1;

assign icmp_ln18_1_fu_244_p2 = ((fpsy_sig_fu_234_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_256_p2 = ((fpsx_exp_fu_202_p3 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln18_3_fu_262_p2 = ((fpsx_sig_fu_210_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_238_p2 = ((fpsy_exp_fu_226_p3 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln715_fu_357_p2 = ((t_7_fu_344_p1 == t_6_fu_331_p1) ? 1'b1 : 1'b0);

assign icmp_ln717_1_fu_389_p2 = ((tmp_5_fu_373_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln717_fu_383_p2 = ((tmp_fu_363_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln733_1_fu_280_p2 = ((fpsy_sig_fu_234_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln733_fu_274_p2 = ((fpsy_exp_fu_226_p3 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln737_1_fu_298_p2 = ((fpsx_sig_fu_210_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln737_fu_292_p2 = ((fpsx_exp_fu_202_p3 == 11'd0) ? 1'b1 : 1'b0);

assign or_ln717_1_fu_399_p2 = (icmp_ln737_1_reg_604 | icmp_ln717_1_reg_648);

assign or_ln717_fu_395_p2 = (icmp_ln733_1_reg_591 | icmp_ln717_reg_643);

assign select_ln780_fu_492_p3 = ((fpsy_sign_reg_568[0:0] == 1'b1) ? 64'd13833125093779451160 : 64'd4609753056924675352);

assign t_1_fu_543_p3 = {{fpsy_sign_reg_568}, {63'd0}};

assign t_2_fu_532_p3 = {{fpsy_sign_reg_568}, {63'd4609753056924675352}};

assign t_3_fu_521_p3 = {{fpsy_sign_reg_568}, {63'd4614256656552045848}};

assign t_4_fu_510_p3 = {{fpsy_sign_reg_568}, {63'd0}};

assign t_5_fu_499_p3 = {{fpsy_sign_reg_568}, {63'd4609753056924675352}};

assign t_6_fu_331_p1 = data_2_fu_214_p1[62:0];

assign t_7_fu_344_p1 = data_fu_190_p1[62:0];

assign t_fu_554_p3 = {{fpsy_sign_reg_568}, {63'd4614256656552045848}};

assign tmp_1_fu_310_p3 = {{fpsx_sign_fu_194_p3}, {fpsy_sign_fu_218_p3}};

assign tmp_5_fu_373_p4 = {{data_fu_190_p1[62:52]}};

assign tmp_fu_363_p4 = {{data_2_fu_214_p1[62:52]}};

assign trunc_ln793_fu_442_p1 = bitcast_ln793_fu_424_p1[62:0];

assign trunc_ln797_fu_475_p1 = bitcast_ln797_fu_458_p1[62:0];

assign xor_ln1_fu_446_p3 = {{xor_ln793_fu_436_p2}, {trunc_ln793_fu_442_p1}};

assign xor_ln793_fu_436_p2 = (bit_sel_fu_428_p3 ^ 1'd1);

assign xor_ln797_fu_469_p2 = (bit_sel1_fu_461_p3 ^ 1'd1);

assign xor_ln_fu_479_p3 = {{xor_ln797_fu_469_p2}, {trunc_ln797_fu_475_p1}};

assign zext_ln479_1_fu_348_p1 = t_7_fu_344_p1;

assign zext_ln479_fu_335_p1 = t_6_fu_331_p1;

always @ (posedge ap_clk) begin
    a_reg_626[63] <= 1'b0;
    b_reg_633[63] <= 1'b0;
end

endmodule //equalStep_baseline_atan2_cordic_double_s
