// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *) module equalStep_baseline_ctlz_81_81_1_1 (din,dout);

parameter din_WIDTH=1;
parameter dout_WIDTH=1;


input [din_WIDTH-1:0] din;
output [dout_WIDTH-1:0] dout;

reg [dout_WIDTH-1:0] dout_tmp;



always @ (din) begin  
    if (din[80] == 1'b1) begin
        dout_tmp = 0; 
    end else if (din[79] == 1'b1) begin
        dout_tmp = 1; 
    end else if (din[78] == 1'b1) begin
        dout_tmp = 2; 
    end else if (din[77] == 1'b1) begin
        dout_tmp = 3; 
    end else if (din[76] == 1'b1) begin
        dout_tmp = 4; 
    end else if (din[75] == 1'b1) begin
        dout_tmp = 5; 
    end else if (din[74] == 1'b1) begin
        dout_tmp = 6; 
    end else if (din[73] == 1'b1) begin
        dout_tmp = 7; 
    end else if (din[72] == 1'b1) begin
        dout_tmp = 8; 
    end else if (din[71] == 1'b1) begin
        dout_tmp = 9; 
    end else if (din[70] == 1'b1) begin
        dout_tmp = 10; 
    end else if (din[69] == 1'b1) begin
        dout_tmp = 11; 
    end else if (din[68] == 1'b1) begin
        dout_tmp = 12; 
    end else if (din[67] == 1'b1) begin
        dout_tmp = 13; 
    end else if (din[66] == 1'b1) begin
        dout_tmp = 14; 
    end else if (din[65] == 1'b1) begin
        dout_tmp = 15; 
    end else if (din[64] == 1'b1) begin
        dout_tmp = 16; 
    end else if (din[63] == 1'b1) begin
        dout_tmp = 17; 
    end else if (din[62] == 1'b1) begin
        dout_tmp = 18; 
    end else if (din[61] == 1'b1) begin
        dout_tmp = 19; 
    end else if (din[60] == 1'b1) begin
        dout_tmp = 20; 
    end else if (din[59] == 1'b1) begin
        dout_tmp = 21; 
    end else if (din[58] == 1'b1) begin
        dout_tmp = 22; 
    end else if (din[57] == 1'b1) begin
        dout_tmp = 23; 
    end else if (din[56] == 1'b1) begin
        dout_tmp = 24; 
    end else if (din[55] == 1'b1) begin
        dout_tmp = 25; 
    end else if (din[54] == 1'b1) begin
        dout_tmp = 26; 
    end else if (din[53] == 1'b1) begin
        dout_tmp = 27; 
    end else if (din[52] == 1'b1) begin
        dout_tmp = 28; 
    end else if (din[51] == 1'b1) begin
        dout_tmp = 29; 
    end else if (din[50] == 1'b1) begin
        dout_tmp = 30; 
    end else if (din[49] == 1'b1) begin
        dout_tmp = 31; 
    end else if (din[48] == 1'b1) begin
        dout_tmp = 32; 
    end else if (din[47] == 1'b1) begin
        dout_tmp = 33; 
    end else if (din[46] == 1'b1) begin
        dout_tmp = 34; 
    end else if (din[45] == 1'b1) begin
        dout_tmp = 35; 
    end else if (din[44] == 1'b1) begin
        dout_tmp = 36; 
    end else if (din[43] == 1'b1) begin
        dout_tmp = 37; 
    end else if (din[42] == 1'b1) begin
        dout_tmp = 38; 
    end else if (din[41] == 1'b1) begin
        dout_tmp = 39; 
    end else if (din[40] == 1'b1) begin
        dout_tmp = 40; 
    end else if (din[39] == 1'b1) begin
        dout_tmp = 41; 
    end else if (din[38] == 1'b1) begin
        dout_tmp = 42; 
    end else if (din[37] == 1'b1) begin
        dout_tmp = 43; 
    end else if (din[36] == 1'b1) begin
        dout_tmp = 44; 
    end else if (din[35] == 1'b1) begin
        dout_tmp = 45; 
    end else if (din[34] == 1'b1) begin
        dout_tmp = 46; 
    end else if (din[33] == 1'b1) begin
        dout_tmp = 47; 
    end else if (din[32] == 1'b1) begin
        dout_tmp = 48; 
    end else if (din[31] == 1'b1) begin
        dout_tmp = 49; 
    end else if (din[30] == 1'b1) begin
        dout_tmp = 50; 
    end else if (din[29] == 1'b1) begin
        dout_tmp = 51; 
    end else if (din[28] == 1'b1) begin
        dout_tmp = 52; 
    end else if (din[27] == 1'b1) begin
        dout_tmp = 53; 
    end else if (din[26] == 1'b1) begin
        dout_tmp = 54; 
    end else if (din[25] == 1'b1) begin
        dout_tmp = 55; 
    end else if (din[24] == 1'b1) begin
        dout_tmp = 56; 
    end else if (din[23] == 1'b1) begin
        dout_tmp = 57; 
    end else if (din[22] == 1'b1) begin
        dout_tmp = 58; 
    end else if (din[21] == 1'b1) begin
        dout_tmp = 59; 
    end else if (din[20] == 1'b1) begin
        dout_tmp = 60; 
    end else if (din[19] == 1'b1) begin
        dout_tmp = 61; 
    end else if (din[18] == 1'b1) begin
        dout_tmp = 62; 
    end else if (din[17] == 1'b1) begin
        dout_tmp = 63; 
    end else if (din[16] == 1'b1) begin
        dout_tmp = 64; 
    end else if (din[15] == 1'b1) begin
        dout_tmp = 65; 
    end else if (din[14] == 1'b1) begin
        dout_tmp = 66; 
    end else if (din[13] == 1'b1) begin
        dout_tmp = 67; 
    end else if (din[12] == 1'b1) begin
        dout_tmp = 68; 
    end else if (din[11] == 1'b1) begin
        dout_tmp = 69; 
    end else if (din[10] == 1'b1) begin
        dout_tmp = 70; 
    end else if (din[9] == 1'b1) begin
        dout_tmp = 71; 
    end else if (din[8] == 1'b1) begin
        dout_tmp = 72; 
    end else if (din[7] == 1'b1) begin
        dout_tmp = 73; 
    end else if (din[6] == 1'b1) begin
        dout_tmp = 74; 
    end else if (din[5] == 1'b1) begin
        dout_tmp = 75; 
    end else if (din[4] == 1'b1) begin
        dout_tmp = 76; 
    end else if (din[3] == 1'b1) begin
        dout_tmp = 77; 
    end else if (din[2] == 1'b1) begin
        dout_tmp = 78; 
    end else if (din[1] == 1'b1) begin
        dout_tmp = 79; 
    end else if (din[0] == 1'b1) begin
        dout_tmp = 80;
    end else begin
        dout_tmp = 81;
    end
end


assign dout = dout_tmp;




endmodule
