// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="equalStep_baseline_equalStep_baseline,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=16.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.572444,HLS_SYN_LAT=364673,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=3462,HLS_SYN_LUT=8008,HLS_VERSION=2025_1}" *)

module equalStep_baseline (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imStack_address0,
        imStack_ce0,
        imStack_q0,
        wrappedPhase_address0,
        wrappedPhase_ce0,
        wrappedPhase_we0,
        wrappedPhase_d0,
        mod_r_address0,
        mod_r_ce0,
        mod_r_we0,
        mod_r_d0
);

parameter    ap_ST_fsm_state1 = 45'd1;
parameter    ap_ST_fsm_state2 = 45'd2;
parameter    ap_ST_fsm_state3 = 45'd4;
parameter    ap_ST_fsm_state4 = 45'd8;
parameter    ap_ST_fsm_state5 = 45'd16;
parameter    ap_ST_fsm_state6 = 45'd32;
parameter    ap_ST_fsm_state7 = 45'd64;
parameter    ap_ST_fsm_state8 = 45'd128;
parameter    ap_ST_fsm_state9 = 45'd256;
parameter    ap_ST_fsm_state10 = 45'd512;
parameter    ap_ST_fsm_state11 = 45'd1024;
parameter    ap_ST_fsm_state12 = 45'd2048;
parameter    ap_ST_fsm_state13 = 45'd4096;
parameter    ap_ST_fsm_state14 = 45'd8192;
parameter    ap_ST_fsm_state15 = 45'd16384;
parameter    ap_ST_fsm_state16 = 45'd32768;
parameter    ap_ST_fsm_state17 = 45'd65536;
parameter    ap_ST_fsm_state18 = 45'd131072;
parameter    ap_ST_fsm_state19 = 45'd262144;
parameter    ap_ST_fsm_state20 = 45'd524288;
parameter    ap_ST_fsm_state21 = 45'd1048576;
parameter    ap_ST_fsm_state22 = 45'd2097152;
parameter    ap_ST_fsm_state23 = 45'd4194304;
parameter    ap_ST_fsm_state24 = 45'd8388608;
parameter    ap_ST_fsm_state25 = 45'd16777216;
parameter    ap_ST_fsm_state26 = 45'd33554432;
parameter    ap_ST_fsm_state27 = 45'd67108864;
parameter    ap_ST_fsm_state28 = 45'd134217728;
parameter    ap_ST_fsm_state29 = 45'd268435456;
parameter    ap_ST_fsm_state30 = 45'd536870912;
parameter    ap_ST_fsm_state31 = 45'd1073741824;
parameter    ap_ST_fsm_state32 = 45'd2147483648;
parameter    ap_ST_fsm_state33 = 45'd4294967296;
parameter    ap_ST_fsm_state34 = 45'd8589934592;
parameter    ap_ST_fsm_state35 = 45'd17179869184;
parameter    ap_ST_fsm_state36 = 45'd34359738368;
parameter    ap_ST_fsm_state37 = 45'd68719476736;
parameter    ap_ST_fsm_state38 = 45'd137438953472;
parameter    ap_ST_fsm_state39 = 45'd274877906944;
parameter    ap_ST_fsm_state40 = 45'd549755813888;
parameter    ap_ST_fsm_state41 = 45'd1099511627776;
parameter    ap_ST_fsm_state42 = 45'd2199023255552;
parameter    ap_ST_fsm_state43 = 45'd4398046511104;
parameter    ap_ST_fsm_state44 = 45'd8796093022208;
parameter    ap_ST_fsm_state45 = 45'd17592186044416;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [14:0] imStack_address0;
output   imStack_ce0;
input  [15:0] imStack_q0;
output  [11:0] wrappedPhase_address0;
output   wrappedPhase_ce0;
output   wrappedPhase_we0;
output  [63:0] wrappedPhase_d0;
output  [11:0] mod_r_address0;
output   mod_r_ce0;
output   mod_r_we0;
output  [63:0] mod_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [44:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] add_ln34_fu_162_p2;
reg   [6:0] add_ln34_reg_257;
wire    ap_CS_fsm_state2;
wire   [5:0] trunc_ln34_fu_168_p1;
reg   [5:0] trunc_ln34_reg_262;
wire   [11:0] tmp_1_fu_172_p3;
reg   [11:0] tmp_1_reg_267;
wire   [6:0] add_ln35_fu_186_p2;
reg   [6:0] add_ln35_reg_275;
wire    ap_CS_fsm_state3;
wire   [5:0] trunc_ln47_fu_192_p1;
reg   [5:0] trunc_ln47_reg_280;
wire   [11:0] add_ln47_fu_201_p2;
reg   [11:0] add_ln47_reg_285;
wire   [63:0] zext_ln47_1_fu_222_p1;
reg   [63:0] zext_ln47_1_reg_296;
wire    ap_CS_fsm_state6;
wire   [63:0] grp_fu_135_p2;
reg   [63:0] mul_reg_301;
wire    ap_CS_fsm_state9;
wire   [63:0] grp_fu_139_p2;
reg   [63:0] mul1_reg_306;
wire   [63:0] grp_fu_131_p2;
reg   [63:0] add_reg_311;
wire    ap_CS_fsm_state14;
wire   [63:0] grp_fu_143_p2;
reg   [63:0] tmp_6_reg_316;
wire    ap_CS_fsm_state44;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_done;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_idle;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_ready;
wire   [14:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_imStack_address0;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_imStack_ce0;
wire   [63:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t2_out;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t2_out_ap_vld;
wire   [63:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t1_out;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t1_out_ap_vld;
wire   [63:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_din0;
wire   [63:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_din1;
wire   [0:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_opcode;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_ce;
wire   [63:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_din0;
wire   [63:0] grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_din1;
wire    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_ce;
wire    grp_atan2_cordic_double_s_fu_123_ap_start;
wire    grp_atan2_cordic_double_s_fu_123_ap_done;
wire    grp_atan2_cordic_double_s_fu_123_ap_idle;
wire    grp_atan2_cordic_double_s_fu_123_ap_ready;
wire   [63:0] grp_atan2_cordic_double_s_fu_123_ap_return;
wire   [63:0] grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_din0;
wire   [63:0] grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_din1;
wire   [0:0] grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_opcode;
wire    grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_ce;
reg   [6:0] j_reg_98;
wire   [0:0] icmp_ln34_fu_156_p2;
wire    ap_CS_fsm_state45;
reg    grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start_reg;
wire   [0:0] icmp_ln35_fu_180_p2;
wire    ap_CS_fsm_state4;
reg    grp_atan2_cordic_double_s_fu_123_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [6:0] i_fu_60;
reg    wrappedPhase_we0_local;
wire   [63:0] bitcast_ln47_fu_226_p1;
reg    wrappedPhase_ce0_local;
reg    mod_r_we0_local;
wire   [63:0] bitcast_ln48_fu_231_p1;
reg    mod_r_ce0_local;
reg   [63:0] grp_fu_131_p0;
reg   [63:0] grp_fu_131_p1;
wire    ap_CS_fsm_state10;
reg   [63:0] grp_fu_135_p0;
reg   [63:0] grp_fu_135_p1;
wire    ap_CS_fsm_state15;
wire   [11:0] zext_ln47_fu_197_p1;
reg   [1:0] grp_fu_131_opcode;
reg    grp_fu_131_ce;
reg    grp_fu_135_ce;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_fu_139_ce;
reg   [44:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 45'd1;
#0 grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start_reg = 1'b0;
#0 grp_atan2_cordic_double_s_fu_123_ap_start_reg = 1'b0;
#0 i_fu_60 = 7'd0;
end

equalStep_baseline_equalStep_baseline_Pipeline_VITIS_LOOP_40_4 grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start),
    .ap_done(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_done),
    .ap_idle(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_idle),
    .ap_ready(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_ready),
    .zext_ln34(trunc_ln34_reg_262),
    .zext_ln35(trunc_ln47_reg_280),
    .imStack_address0(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_imStack_address0),
    .imStack_ce0(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_imStack_ce0),
    .imStack_q0(imStack_q0),
    .Phi_t2_out(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t2_out),
    .Phi_t2_out_ap_vld(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t2_out_ap_vld),
    .Phi_t1_out(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t1_out),
    .Phi_t1_out_ap_vld(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t1_out_ap_vld),
    .grp_fu_131_p_din0(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_din0),
    .grp_fu_131_p_din1(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_din1),
    .grp_fu_131_p_opcode(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_opcode),
    .grp_fu_131_p_dout0(grp_fu_131_p2),
    .grp_fu_131_p_ce(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_ce),
    .grp_fu_135_p_din0(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_din0),
    .grp_fu_135_p_din1(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_din1),
    .grp_fu_135_p_dout0(grp_fu_135_p2),
    .grp_fu_135_p_ce(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_ce)
);

equalStep_baseline_atan2_cordic_double_s grp_atan2_cordic_double_s_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_atan2_cordic_double_s_fu_123_ap_start),
    .ap_done(grp_atan2_cordic_double_s_fu_123_ap_done),
    .ap_idle(grp_atan2_cordic_double_s_fu_123_ap_idle),
    .ap_ready(grp_atan2_cordic_double_s_fu_123_ap_ready),
    .y_in(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t1_out),
    .x_in(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t2_out),
    .ap_return(grp_atan2_cordic_double_s_fu_123_ap_return),
    .grp_fu_131_p_din0(grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_din0),
    .grp_fu_131_p_din1(grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_din1),
    .grp_fu_131_p_opcode(grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_opcode),
    .grp_fu_131_p_dout0(grp_fu_131_p2),
    .grp_fu_131_p_ce(grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_ce)
);

equalStep_baseline_dadddsub_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadddsub_64ns_64ns_64_5_full_dsp_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_131_p0),
    .din1(grp_fu_131_p1),
    .opcode(grp_fu_131_opcode),
    .ce(grp_fu_131_ce),
    .dout(grp_fu_131_p2)
);

equalStep_baseline_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_135_p0),
    .din1(grp_fu_135_p1),
    .ce(grp_fu_135_ce),
    .dout(grp_fu_135_p2)
);

equalStep_baseline_dmul_64ns_64ns_64_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t2_out),
    .din1(grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t2_out),
    .ce(grp_fu_139_ce),
    .dout(grp_fu_139_p2)
);

equalStep_baseline_dsqrt_64ns_64ns_64_30_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 30 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsqrt_64ns_64ns_64_30_no_dsp_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(64'd0),
    .din1(add_reg_311),
    .ce(1'b1),
    .dout(grp_fu_143_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_atan2_cordic_double_s_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_atan2_cordic_double_s_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_atan2_cordic_double_s_fu_123_ap_ready == 1'b1)) begin
            grp_atan2_cordic_double_s_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln35_fu_180_p2 == 1'd0))) begin
            grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start_reg <= 1'b1;
        end else if ((grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_ready == 1'b1)) begin
            grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_60 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln35_fu_180_p2 == 1'd1))) begin
        i_fu_60 <= add_ln34_reg_257;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        j_reg_98 <= add_ln35_reg_275;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln34_fu_156_p2 == 1'd0))) begin
        j_reg_98 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln34_reg_257 <= add_ln34_fu_162_p2;
        tmp_1_reg_267[11 : 6] <= tmp_1_fu_172_p3[11 : 6];
        trunc_ln34_reg_262 <= trunc_ln34_fu_168_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln35_reg_275 <= add_ln35_fu_186_p2;
        add_ln47_reg_285 <= add_ln47_fu_201_p2;
        trunc_ln47_reg_280 <= trunc_ln47_fu_192_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_reg_311 <= grp_fu_131_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        mul1_reg_306 <= grp_fu_139_p2;
        mul_reg_301 <= grp_fu_135_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        tmp_6_reg_316 <= grp_fu_143_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        zext_ln47_1_reg_296[11 : 0] <= zext_ln47_1_fu_222_p1[11 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

always @ (*) begin
    if ((grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_atan2_cordic_double_s_fu_123_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln34_fu_156_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln34_fu_156_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_131_ce = grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_131_ce = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_ce;
    end else begin
        grp_fu_131_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_131_opcode = grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_131_opcode = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_131_opcode = 2'd0;
    end else begin
        grp_fu_131_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_131_p0 = grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_131_p0 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_131_p0 = mul_reg_301;
    end else begin
        grp_fu_131_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_131_p1 = grp_atan2_cordic_double_s_fu_123_grp_fu_131_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_131_p1 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_131_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_131_p1 = mul1_reg_306;
    end else begin
        grp_fu_131_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_135_ce = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state6) & (grp_atan2_cordic_double_s_fu_123_ap_done == 1'b1)))) begin
        grp_fu_135_ce = 1'b1;
    end else begin
        grp_fu_135_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_135_p0 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_135_p0 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t1_out;
    end else begin
        grp_fu_135_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_135_p1 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_grp_fu_135_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_135_p1 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_Phi_t1_out;
    end else begin
        grp_fu_135_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state6) & (grp_atan2_cordic_double_s_fu_123_ap_done == 1'b1)))) begin
        grp_fu_139_ce = 1'b1;
    end else begin
        grp_fu_139_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        mod_r_ce0_local = 1'b1;
    end else begin
        mod_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        mod_r_we0_local = 1'b1;
    end else begin
        mod_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_atan2_cordic_double_s_fu_123_ap_done == 1'b1))) begin
        wrappedPhase_ce0_local = 1'b1;
    end else begin
        wrappedPhase_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_atan2_cordic_double_s_fu_123_ap_done == 1'b1))) begin
        wrappedPhase_we0_local = 1'b1;
    end else begin
        wrappedPhase_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln34_fu_156_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln35_fu_180_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_atan2_cordic_double_s_fu_123_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_fu_162_p2 = (i_fu_60 + 7'd1);

assign add_ln35_fu_186_p2 = (j_reg_98 + 7'd1);

assign add_ln47_fu_201_p2 = (tmp_1_reg_267 + zext_ln47_fu_197_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln47_fu_226_p1 = grp_atan2_cordic_double_s_fu_123_ap_return;

assign bitcast_ln48_fu_231_p1 = tmp_6_reg_316;

assign grp_atan2_cordic_double_s_fu_123_ap_start = grp_atan2_cordic_double_s_fu_123_ap_start_reg;

assign grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_ap_start_reg;

assign icmp_ln34_fu_156_p2 = ((i_fu_60 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_180_p2 = ((j_reg_98 == 7'd64) ? 1'b1 : 1'b0);

assign imStack_address0 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_imStack_address0;

assign imStack_ce0 = grp_equalStep_baseline_Pipeline_VITIS_LOOP_40_4_fu_109_imStack_ce0;

assign mod_r_address0 = zext_ln47_1_reg_296;

assign mod_r_ce0 = mod_r_ce0_local;

assign mod_r_d0 = bitcast_ln48_fu_231_p1;

assign mod_r_we0 = mod_r_we0_local;

assign tmp_1_fu_172_p3 = {{trunc_ln34_fu_168_p1}, {6'd0}};

assign trunc_ln34_fu_168_p1 = i_fu_60[5:0];

assign trunc_ln47_fu_192_p1 = j_reg_98[5:0];

assign wrappedPhase_address0 = zext_ln47_1_fu_222_p1;

assign wrappedPhase_ce0 = wrappedPhase_ce0_local;

assign wrappedPhase_d0 = bitcast_ln47_fu_226_p1;

assign wrappedPhase_we0 = wrappedPhase_we0_local;

assign zext_ln47_1_fu_222_p1 = add_ln47_reg_285;

assign zext_ln47_fu_197_p1 = j_reg_98;

always @ (posedge ap_clk) begin
    tmp_1_reg_267[5:0] <= 6'b000000;
    zext_ln47_1_reg_296[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //equalStep_baseline
